using System;using System.IO;using System.Linq;using System.Collections.Generic;
class AutoBridgeTests {
 static void A(bool ok,string why){if(!ok)throw new Exception(why);}
 static void Main(string[] args){string root=Path.Combine(Path.GetTempPath(),"autobridge-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{byte[] original=File.ReadAllBytes(args[0]),template=File.ReadAllBytes(Path.Combine(Core.Base,"templates/bridge-x64.dll")),generated=AutoBridge.Generate(original,template);File.WriteAllBytes(Path.Combine(root,"generated.dll"),generated);if(args.Length>1)File.WriteAllBytes(args[1],generated);var src=new PeImage(original);var proxy=new PeImage(generated);A(src.Symbols.Count==proxy.Symbols.Count,"export count");A(proxy.Find("SteamAPI_InitFlat").Address!=src.Find("SteamAPI_InitFlat").Address,"init routed");A(proxy.IsForwarder(proxy.Find("SteamAPI_GetHSteamPipe")),"original forwarder");A(proxy.Ascii(proxy.Map(proxy.Find("SteamAPI_GetHSteamPipe").Address))=="steam_api64_original.SteamAPI_GetHSteamPipe","forwarded name");A(proxy.ExportBase==src.ExportBase&&proxy.Symbols.Select(e=>e.Ordinal).SequenceEqual(src.Symbols.Select(e=>e.Ordinal)),"ordinal identity");
 string client=Path.Combine(root,"steamclient64.dll"),api=Path.Combine(root,"steam_api64.dll");File.WriteAllText(client,"client fixture");File.WriteAllBytes(api,original);var plan=new AutoPlan{Root=root,Steam=root,ClientHash=Core.Hash(client)};var f=new AutoFile{Path="steam_api64.dll",Backup="steam_api64_original.dll",OriginalHash=Core.Hash(api),PatchedHash=Core.Hash(Path.Combine(root,"generated.dll")),Generated=generated};plan.Files.Add(f);AutoBridge.Install(plan,Console.WriteLine);A(Core.Hash(api)==f.PatchedHash&&AutoBridge.HasState(root),"generic install state");AutoBridge.Restore(root,Console.WriteLine);A(Core.Hash(api)==f.OriginalHash&&!AutoBridge.HasState(root)&&!File.Exists(Path.Combine(root,f.Backup)),"restore/archive");bool rejected=false;AutoBridge.Install(plan,Console.WriteLine);File.WriteAllText(api,"updated game");try{AutoBridge.Restore(root,Console.WriteLine);}catch{rejected=true;}A(rejected&&File.ReadAllText(api)=="updated game","updated file protected");File.WriteAllBytes(api,original);AutoBridge.Restore(root,Console.WriteLine);
 rejected=false;try{AutoBridge.Install(plan,message=>{throw new Exception("Injected callback failure after write");});}catch{rejected=true;}A(rejected&&Core.Hash(api)==f.OriginalHash,"generic rollback");AutoBridge.Restore(root,Console.WriteLine);
 var invalidAccessor=(byte[])original.Clone();invalidAccessor[src.Map(src.Find(src.Find("SteamAPI_SteamFriends_v018")!=null?"SteamAPI_SteamFriends_v018":"SteamAPI_SteamTimeline_v004").Address)]=0x90;rejected=false;try{AutoBridge.Generate(invalidAccessor,template);}catch{rejected=true;}A(rejected,"unknown accessor refusal");
 A(AutoBridge.SupportedClientPattern(new HashSet<string>{"SteamClient017","SteamClient021"},"670d654aa3255c5061cf0236a1cdbb2f5076cbd5ae44f613b6f4921558e83e2d"),"verified Rizline SDK allowed");A(!AutoBridge.SupportedClientPattern(new HashSet<string>{"SteamClient017","SteamClient021"},"unknown"),"unverified 021 SDK refused");A(AutoBridge.SupportedClientPattern(new HashSet<string>{"SteamClient017","SteamClient023"},"existing"),"023 compatibility retained");var invalid=(byte[])original.Clone();invalid[0]=0;rejected=false;try{AutoBridge.Generate(invalid,template);}catch{rejected=true;}A(rejected,"invalid PE refusal");Console.WriteLine("PASS: local export generation, named/ordinal preservation, original forwarding, init interception, generic install/restore, archive, update refusal, rollback, malformed PE rejection.");}finally{Directory.Delete(root,true);}}
}
