using System;using System.IO;using System.Collections.Generic;
class Tests {
 static void Assert(bool v,string message){if(!v)throw new Exception(message);}
 static void Main(){string root=Path.Combine(Path.GetTempPath(),"fixertest-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{
 var v=Core.Vdf("// comment\n\"libraryfolders\" { \"0\" { \"path\" \"D:\\\\Steam Library\" } \"1\" \"E:\\\\Steam\" }");var libs=(Dictionary<string,object>)v["libraryfolders"];Assert((string)((Dictionary<string,object>)libs["0"])["path"]==@"D:\Steam Library","escaped VDF");Assert((string)libs["1"]==@"E:\Steam","old VDF");bool blocked=false;try{Core.Inside(root,"../escape");}catch{blocked=true;}Assert(blocked,"path traversal");
 string modules=Path.Combine(root,"modules/gmod");Directory.CreateDirectory(modules);File.WriteAllText(Path.Combine(modules,"payload"),"patched");string game=Path.Combine(root,"steamapps/common/Test");Directory.CreateDirectory(game);File.WriteAllText(Path.Combine(game,"gmod.exe"),"");File.WriteAllText(Path.Combine(game,"api.dll"),"original");var t=new Target{Path="api.dll",Backup="backup/api.dll",Original=Core.Hash(Path.Combine(game,"api.dll")),Patched=Core.Hash(Path.Combine(modules,"payload")),Payload="payload",PayloadHash=Core.Hash(Path.Combine(modules,"payload"))};var m=new Module{Id="gmod",AppId="4000",Name="Fixture",Marker="gmod.exe",Targets=new[]{t},Preflight=""};Core.Base=root;Core.Modules=new[]{m};File.WriteAllText(Path.Combine(root,"steamapps/appmanifest_4000.acf"),"\"AppState\" { \"appid\" \"4000\" \"name\" \"Fixture\" \"installdir\" \"Test\" }");var games=Core.Scan(root,Console.WriteLine);Assert(games.Count==1&&games[0].Status=="Ready","scan and readiness");string other=Path.Combine(root,"Other Library");Directory.CreateDirectory(Path.Combine(other,"steamapps/common/Unknown"));File.WriteAllText(Path.Combine(other,"steamapps/appmanifest_999.acf"),"\"AppState\" { \"appid\" \"999\" \"name\" \"Other\" \"installdir\" \"Unknown\" }");File.WriteAllText(Path.Combine(root,"steamapps/libraryfolders.vdf"),"\"libraryfolders\" { \"1\" { \"path\" \""+other+"\" } }");var multiple=Core.Scan(root,Console.WriteLine);Assert(multiple.Count==2&&multiple[1].Status=="Unsupported","multiple libraries and unknown game");var g=games[0];Core.Apply(g,false,Console.WriteLine);Assert(g.Status=="Patched","install");Core.Apply(g,false,Console.WriteLine);Assert(g.Status=="Patched","idempotence");Core.Apply(g,true,Console.WriteLine);Assert(g.Status=="Ready"&&Core.Hash(Path.Combine(game,"api.dll"))==t.Original,"restore");
 blocked=false;try{Core.Apply(g,false,message=>{throw new Exception("Injected failure after replacement");});}catch{blocked=true;}Assert(blocked&&Core.Hash(Path.Combine(game,"api.dll"))==t.Original,"rollback after write failure");
 File.WriteAllText(Path.Combine(modules,"payload"),"corrupt");blocked=false;try{Core.Apply(g,false,Console.WriteLine);}catch{blocked=true;}Assert(blocked&&Core.Hash(Path.Combine(game,"api.dll"))==t.Original,"damaged payload leaves input");File.WriteAllText(Path.Combine(game,"api.dll"),"unknown");Core.Inspect(g);Assert(g.Status=="Mismatch","unknown version");File.WriteAllText(Path.Combine(game,"api.dll"),"original");File.WriteAllText(Path.Combine(game,"backup/api.dll"),"corrupt");Core.Inspect(g);Assert(g.Status=="Mismatch","bad backup");
 blocked=false;try{LegacyDeltaPatch.Apply(new byte[0],new byte[0]);}catch{blocked=true;}Assert(blocked,"malformed delta");Console.WriteLine("PASS: VDF old/new, multiple libraries, unknown game, path confinement, scan, matching, installation, idempotence, restore, rollback after write failure, payload rejection, version rejection, backup rejection, malformed delta.");
 }finally{Directory.Delete(root,true);}}
}
