using System;using System.IO;using Microsoft.Win32;
class RizlinePlanTests {
 static void Main(string[] args){string tmp=Path.Combine(Path.GetTempPath(),"rizline-plan-"+Guid.NewGuid().ToString("N"));string key=@"Software\Valve\Steam";using(var registry=Registry.CurrentUser.CreateSubKey(key)){object old=registry.GetValue("SteamPath");try{
 Directory.CreateDirectory(tmp);registry.SetValue("SteamPath",tmp);File.WriteAllText(Path.Combine(tmp,"steamclient64.dll"),"mock backend");string root=Path.Combine(tmp,"Rizline");Directory.CreateDirectory(root);
 var report=new AnalysisReport{Root=root,Steam=tmp};foreach(string rel in new[]{"Rizline_Data/Plugins/x86_64/steam_api64.dll","Editor/Rizline Editor_Data/Plugins/x86_64/steam_api64.dll"}){string file=Path.Combine(root,rel);Directory.CreateDirectory(Path.GetDirectoryName(file));File.Copy(args[0],file);var info=Analyzer.ReadBinary(file,root);report.Files.Add(info);foreach(var e in info.Evidence)report.Probes["x64|"+e.Interface]="PRESENT";}
 report.Probes["x64|LegacySteamBridgeABI"]="PRESENT";report.Probes["x64|SteamClient023"]="UNAVAILABLE: mock legacy client";report.Probes["x64|STEAMTIMELINE_INTERFACE_V004"]="UNAVAILABLE: mock legacy client";
 var plan=AutoBridge.Plan(new Game{Root=root},report);if(plan.Files.Count!=2)throw new Exception("Both SDKs must produce plans");if(!LaunchProfiles.SelectInjectionFile("Rizline.exe",plan).Path.StartsWith("Rizline_Data"))throw new Exception("Wrong main SDK");if(!LaunchProfiles.SelectInjectionFile("Editor/Rizline Editor.exe",plan).Path.StartsWith("Editor"))throw new Exception("Wrong editor SDK");foreach(var f in plan.Files)if(Core.Hash(Path.Combine(root,f.Path))!=f.OriginalHash)throw new Exception("Plan modified source SDK");Console.WriteLine("PASS: actual uploaded Rizline SDK plan generation for game/editor, mock legacy probes, Timeline rule, matching executable and unchanged source files. No live Steam/game execution.");
 }finally{if(old==null)registry.DeleteValue("SteamPath",false);else registry.SetValue("SteamPath",old);if(Directory.Exists(tmp))Directory.Delete(tmp,true);}}}
}
