using System;using System.IO;using System.Text;using System.Collections.Generic;using System.Web.Script.Serialization;using System.Diagnostics;
public class ExportSymbol {public string Name;public uint Ordinal,Address;}
public class PeImage {
 public byte[] Bytes;public int Pe,Opt,SectionTable,Sections,OptSize;public uint ExportRva,ExportSize,ExportBase,FunctionCount;public List<ExportSymbol> Symbols=new List<ExportSymbol>();
 public PeImage(byte[] bytes){Bytes=bytes;if(U16(0)!=0x5a4d)throw new Exception("Not PE");Pe=checked((int)U32(0x3c));if(U32(Pe)!=0x4550||U16(Pe+4)!=0x8664)throw new Exception("Only native x64 PE supported by generic builder");Sections=U16(Pe+6);OptSize=U16(Pe+20);Opt=Pe+24;if(U16(Opt)!=0x20b||OptSize<240||Sections<1||Sections>96)throw new Exception("Unsupported PE layout");SectionTable=Opt+OptSize;ExportRva=U32(Opt+112);ExportSize=U32(Opt+116);if(U32(Opt+112+14*8)!=0)throw new Exception("Managed PE cannot use native proxy rule");if(ExportRva==0)throw new Exception("Export table missing");int e=Map(ExportRva);ExportBase=U32(e+16);FunctionCount=U32(e+20);uint names=U32(e+24);if(FunctionCount==0||FunctionCount>10000||names>10000)throw new Exception("Unsupported export count");int functions=Map(U32(e+28)),nameTable=Map(U32(e+32)),ordinalTable=Map(U32(e+36));var byIndex=new Dictionary<int,string>();for(int i=0;i<names;i++){int index=U16(ordinalTable+i*2);if(index>=FunctionCount||byIndex.ContainsKey(index))throw new Exception("Aliased or invalid ordinal unsupported");byIndex[index]=Ascii(Map(U32(nameTable+i*4)));}for(int i=0;i<FunctionCount;i++){string name;byIndex.TryGetValue(i,out name);Symbols.Add(new ExportSymbol{Name=name,Ordinal=ExportBase+(uint)i,Address=U32(functions+i*4)});}}
 public ushort U16(int p){Bounds(p,2);return BitConverter.ToUInt16(Bytes,p);}public uint U32(int p){Bounds(p,4);return BitConverter.ToUInt32(Bytes,p);}void Bounds(int p,int n){if(p<0||p>Bytes.Length-n)throw new Exception("Invalid PE bounds");}
 public int Map(uint va){uint headers=U32(Opt+60);if(va<headers){Bounds(checked((int)va),1);return (int)va;}for(int i=0;i<Sections;i++){int p=SectionTable+i*40;uint start=U32(p+12),size=U32(p+16),raw=U32(p+20);if(va>=start&&(ulong)va<(ulong)start+size){int offset=checked((int)(raw+va-start));Bounds(offset,1);return offset;}}throw new Exception("Invalid PE RVA");}
 public string Ascii(int p){Bounds(p,1);var b=new StringBuilder();for(int n=0;n<2048;n++){Bounds(p+n,1);byte c=Bytes[p+n];if(c==0)return b.ToString();if(c<32||c>126)throw new Exception("Non-ASCII export name");b.Append((char)c);}throw new Exception("Export name too long");}
 public ExportSymbol Find(string name){foreach(var e in Symbols)if(e.Name==name)return e;return null;}
 public bool IsForwarder(ExportSymbol e){return e.Address>=ExportRva&&(ulong)e.Address<(ulong)ExportRva+ExportSize;}
}
public class AutoFile {public string Path,OriginalHash,PatchedHash,Backup;public byte[] Generated;public List<string> Rules=new List<string>();}
public class AutoPlan {public string Root,Steam,ClientHash;public List<AutoFile> Files=new List<AutoFile>();public List<string> Reasons=new List<string>();}
public class AutoState {public string Version,Root;public List<AutoFile> Files=new List<AutoFile>();}
public static class AutoBridge {
 public static string TemplateHash="2c74389f0bd4a323e39d9cd3edafe1526bb8e9cf598ae204bfd61c8b69b98367";
 static uint Align(uint v,uint a){if(a==0||(a&(a-1))!=0)throw new Exception("Invalid PE alignment");return checked((v+a-1)/a*a);}
 static void Put(byte[] b,int at,uint value){Buffer.BlockCopy(BitConverter.GetBytes(value),0,b,at,4);}static string Digest(byte[] bytes){using(var h=System.Security.Cryptography.SHA256.Create())return BitConverter.ToString(h.ComputeHash(bytes)).Replace("-","").ToLowerInvariant();}
 public static void ValidateAccessor(PeImage src,string name){var e=src.Find(name);var context=src.Find("SteamInternal_ContextInit");if(e==null||context==null||src.IsForwarder(e))throw new Exception("SDK accessor not covered: "+name);int p=src.Map(e.Address);byte[] expected=new byte[]{0x48,0x83,0xec,0x28,0x48,0x8d,0x0d,0,0,0,0,0xe8,0,0,0,0,0x48,0x8b,0x00,0x48,0x83,0xc4,0x28,0xc3};for(int i=0;i<expected.Length;i++){if(i>=7&&i<=10||i>=12&&i<=15)continue;if(p+i>=src.Bytes.Length||src.Bytes[p+i]!=expected[i])throw new Exception("Unknown SDK accessor code: "+name);}long callTarget=(long)e.Address+16+BitConverter.ToInt32(src.Bytes,p+12);if(callTarget!=context.Address)throw new Exception("Accessor does not call exported ContextInit: "+name);}
 public static void ValidateSDK(PeImage src){foreach(string name in new[]{"SteamAPI_SteamFriends_v018","SteamAPI_SteamUGC_v021","SteamAPI_SteamRemotePlay_v003","SteamAPI_SteamRemotePlay_v004","SteamAPI_SteamTimeline_v004","SteamAPI_SteamApps_v009"})if(src.Find(name)!=null)ValidateAccessor(src,name);}
 public static bool SupportedClientPattern(HashSet<string> versions,string hash){return versions.Contains("SteamClient017")&&(versions.Contains("SteamClient023")||(versions.Contains("SteamClient021")&&hash=="670d654aa3255c5061cf0236a1cdbb2f5076cbd5ae44f613b6f4921558e83e2d"));}
 public static byte[] Generate(byte[] original,byte[] template){var src=new PeImage(original);ValidateSDK(src);var dst=new PeImage(template);if(src.Find("SteamInternal_SteamAPI_Init")==null||src.Find("SteamAPI_GetHSteamPipe")==null||src.Find("SteamInternal_CreateInterface")==null)throw new Exception("Required Steam API initialization/pipe exports missing");foreach(var e in src.Symbols){if(src.IsForwarder(e))throw new Exception("Existing export forwarder/proxy rejected");if(e.Name!=null&&!e.Name.StartsWith("Steam",StringComparison.Ordinal)&&e.Name!="GetHSteamPipe"&&e.Name!="GetHSteamUser"&&e.Name!="g_pSteamClientGameServer")throw new Exception("Nonstandard export: "+e.Name);}
 var intercept=new Dictionary<string,string>{{"SteamInternal_SteamAPI_Init","BridgeInit"},{"SteamInternal_CreateInterface","BridgeCreate"},{"SteamAPI_InitFlat","BridgeInitFlat"},{"SteamAPI_InitSafe","BridgeInitSafe"},{"SteamAPI_SteamTimeline_v004","BridgeTimeline"},{"SteamInternal_FindOrCreateUserInterface","BridgeFindUser"}};
 uint sectionAlign=dst.U32(dst.Opt+32),fileAlign=dst.U32(dst.Opt+36),lastEnd=0;for(int i=0;i<dst.Sections;i++){int s=dst.SectionTable+i*40;lastEnd=Math.Max(lastEnd,checked(dst.U32(s+12)+Math.Max(dst.U32(s+8),dst.U32(s+16))));}uint rva=Align(lastEnd,sectionAlign),raw=Align((uint)template.Length,fileAlign);int header=dst.SectionTable+dst.Sections*40;if(header+40>dst.U32(dst.Opt+60))throw new Exception("Template has no section header space");for(int i=0;i<40;i++)if(template[header+i]!=0)throw new Exception("Template header space occupied");
 var names=new List<ExportSymbol>();foreach(var e in src.Symbols)if(e.Name!=null)names.Add(e);names.Sort((a,b)=>StringComparer.Ordinal.Compare(a.Name,b.Name));int tableSize=checked(40+(int)src.FunctionCount*4+names.Count*6);var blob=new List<byte>(new byte[tableSize]);Func<string,uint> add=text=>{uint pos=rva+(uint)blob.Count;blob.AddRange(Encoding.ASCII.GetBytes(text));blob.Add(0);return pos;};uint moduleName=add("steam_api64.dll");var func=new uint[src.FunctionCount];foreach(var e in src.Symbols){if(e.Address==0)continue;string hook;if(e.Name!=null&&intercept.TryGetValue(e.Name,out hook)){var impl=dst.Find(hook);if(impl==null||dst.IsForwarder(impl))throw new Exception("Bridge implementation export missing");func[e.Ordinal-src.ExportBase]=impl.Address;}else func[e.Ordinal-src.ExportBase]=add("steam_api64_original."+(e.Name??("#"+e.Ordinal)));}
 int functions=40,namePtr=functions+(int)src.FunctionCount*4,ordPtr=namePtr+names.Count*4;uint[] nameRvas=new uint[names.Count];for(int i=0;i<names.Count;i++)nameRvas[i]=add(names[i].Name);byte[] data=blob.ToArray();Put(data,12,moduleName);Put(data,16,src.ExportBase);Put(data,20,src.FunctionCount);Put(data,24,(uint)names.Count);Put(data,28,rva+(uint)functions);Put(data,32,rva+(uint)namePtr);Put(data,36,rva+(uint)ordPtr);for(int i=0;i<func.Length;i++)Put(data,functions+i*4,func[i]);for(int i=0;i<names.Count;i++){Put(data,namePtr+i*4,nameRvas[i]);Buffer.BlockCopy(BitConverter.GetBytes(checked((ushort)(names[i].Ordinal-src.ExportBase))),0,data,ordPtr+i*2,2);}uint rawSize=Align((uint)data.Length,fileAlign);byte[] output=new byte[checked((int)(raw+rawSize))];Buffer.BlockCopy(template,0,output,0,template.Length);Buffer.BlockCopy(data,0,output,(int)raw,data.Length);Buffer.BlockCopy(Encoding.ASCII.GetBytes(".lexport"),0,output,header,8);Put(output,header+8,(uint)data.Length);Put(output,header+12,rva);Put(output,header+16,rawSize);Put(output,header+20,raw);Put(output,header+36,0x40000040);Buffer.BlockCopy(BitConverter.GetBytes(checked((ushort)(dst.Sections+1))),0,output,dst.Pe+6,2);Put(output,dst.Opt+56,Align(rva+(uint)data.Length,sectionAlign));Put(output,dst.Opt+112,rva);Put(output,dst.Opt+116,(uint)data.Length);Put(output,dst.Opt+112+4*8,0);Put(output,dst.Opt+116+4*8,0);Put(output,dst.Opt+64,0);var check=new PeImage(output);if(check.ExportBase!=src.ExportBase||check.FunctionCount!=src.FunctionCount||check.Symbols.Count!=src.Symbols.Count)throw new Exception("Generated export table validation failed");foreach(var e in src.Symbols){var mapped=check.Symbols[(int)(e.Ordinal-src.ExportBase)];if(e.Name!=mapped.Name||(e.Address==0)!=(mapped.Address==0))throw new Exception("Export identity mismatch");if(mapped.Address!=0&&!intercept.ContainsKey(e.Name??"")){if(!check.IsForwarder(mapped)||check.Ascii(check.Map(mapped.Address))!="steam_api64_original."+(e.Name??("#"+e.Ordinal)))throw new Exception("Forwarder validation failed");}}return output;}
 public static AutoPlan Plan(Game game,AnalysisReport report){var plan=new AutoPlan{Root=game.Root,Steam=report.Steam};if(report.Root!=game.Root)throw new Exception("Analysis belongs to another game");string client=Core.Inside(report.Steam,"steamclient64.dll");plan.ClientHash=Core.Hash(client);string abi;if(!report.Probes.TryGetValue("x64|LegacySteamBridgeABI",out abi)||abi!="PRESENT")throw new Exception("Reanalyze with this version: supported legacy factory ABI must be confirmed");string currentRoot=Core.SteamRoot();if(currentRoot==""||!Path.GetFullPath(currentRoot).TrimEnd(new char[]{'\\','/'}).Equals(Path.GetFullPath(report.Steam).TrimEnd(new char[]{'\\','/'}),StringComparison.OrdinalIgnoreCase))throw new Exception("Selected Steam differs from Steam registry installation; bridge would load another client");Require(report,"SteamClient023",false);Require(report,"SteamClient021",true);Require(report,"SteamClient017",true);string templateFile=Core.Inside(Core.Base,"templates/bridge-x64.dll");if(Core.Hash(templateFile)!=TemplateHash)throw new Exception("Bridge template checksum mismatch");byte[] template=File.ReadAllBytes(templateFile);
 foreach(var file in report.Files){if(!Path.GetFileName(file.File).Equals("steam_api64.dll",StringComparison.OrdinalIgnoreCase)||file.Architecture!="x64")continue;string target=Core.Inside(game.Root,file.File);if(Core.Hash(target)!=file.Hash)throw new Exception("Game changed since analysis");var versions=new HashSet<string>();foreach(var e in file.Evidence)versions.Add(e.Interface);if(!SupportedClientPattern(versions,file.Hash)){plan.Reasons.Add(file.File+": SDK client acquisition pattern not covered");continue;}var item=new AutoFile{Path=file.File,OriginalHash=file.Hash,Backup=Path.Combine(Path.GetDirectoryName(file.File),"steam_api64_original.dll")};if(File.Exists(Core.Inside(game.Root,item.Backup)))throw new Exception("Existing original/proxy backup at "+item.Backup+". Restore with its original installer first.");bool bad=false;foreach(string v in versions){if(v.StartsWith("SteamGameServer",StringComparison.Ordinal))continue;string result;if(!report.Probes.TryGetValue("x64|"+v,out result)||result.StartsWith("UNKNOWN")){plan.Reasons.Add(file.File+": unknown probe result for "+v);bad=true;continue;}if(result=="PRESENT")continue;string older;if(Analyzer.Fallbacks.TryGetValue(v,out older)){Require(report,older,true);item.Rules.Add(v+" -> "+older+" (ABI adapter)");}else if(v=="STEAMTIMELINE_INTERFACE_V004")item.Rules.Add(v+" -> no-op recording interface (recording unavailable)");else {plan.Reasons.Add(file.File+": no rule for "+v);bad=true;}}if(bad)continue;item.Rules.Add("Local SDK accessor machine-code pattern and ContextInit call target verified; export names/ordinals preserved");item.Generated=Generate(File.ReadAllBytes(target),template);item.PatchedHash=Digest(item.Generated);plan.Files.Add(item);}if(plan.Files.Count==0)throw new Exception("No generatable native x64 plan. "+string.Join("; ",plan.Reasons.ToArray()));return plan;}
 static void Require(AnalysisReport r,string v,bool present){string result;if(!r.Probes.TryGetValue("x64|"+v,out result)||(present?result!="PRESENT":!result.StartsWith("UNAVAILABLE")))throw new Exception("Required client condition not confirmed: "+v);}
 public static string Describe(AutoPlan plan){var b=new StringBuilder("本地生成的实验性接口桥接方案；未验证实际游戏启动。\n");foreach(var f in plan.Files){b.AppendLine(f.Path+"\nOriginal="+f.OriginalHash+"\nGenerated="+f.PatchedHash+"\nBackup="+f.Backup);foreach(var rule in f.Rules)b.AppendLine("  "+rule);}foreach(var reason in plan.Reasons)b.AppendLine("NOT COVERED: "+reason);b.AppendLine("原版API继续处理授权、登录和回调。录制时间线等新增功能不可用。游戏自身文件校验、托管初始化检查不在通用桥接规则范围内。\n安装后需从Steam实际启动测试，失败时可还原。");return b.ToString();}
 static string StatePath(string root){return Core.Inside(root,"LegacySteamFixer-Auto/state.json");}
 public static bool HasState(string root){return File.Exists(StatePath(root));}
 static void StopIfActive(string root){foreach(var p in Process.GetProcesses())using(p){string exe;try{exe=p.MainModule.FileName;}catch{continue;}if(exe.StartsWith(Path.GetFullPath(root).TrimEnd(new char[]{'\\'})+"\\",StringComparison.OrdinalIgnoreCase))throw new Exception("Close game and game-folder processes first: "+p.ProcessName);}}
 public static void Install(AutoPlan plan,Action<string> log){if(HasState(plan.Root))throw new Exception("Generic bridge already recorded; restore before reinstall");if(Core.Hash(Core.Inside(plan.Steam,"steamclient64.dll"))!=plan.ClientHash)throw new Exception("Steam changed; reanalyze");StopIfActive(plan.Root);foreach(var f in plan.Files){if(Core.Hash(Core.Inside(plan.Root,f.Path))!=f.OriginalHash||Digest(f.Generated)!=f.PatchedHash||File.Exists(Core.Inside(plan.Root,f.Backup)))throw new Exception("Files changed after plan generation");}string folder=Core.Inside(plan.Root,"LegacySteamFixer-Auto");Directory.CreateDirectory(folder);var state=new AutoState{Version="0.3.0-test1",Root=plan.Root};foreach(var f in plan.Files)state.Files.Add(new AutoFile{Path=f.Path,OriginalHash=f.OriginalHash,PatchedHash=f.PatchedHash,Backup=f.Backup,Rules=f.Rules});string record=StatePath(plan.Root);if(File.Exists(record))throw new Exception("Installation record exists");
 // Persist recoverable intent before any game file is replaced.
 File.WriteAllText(record,new JavaScriptSerializer().Serialize(state),Encoding.UTF8);var changed=new List<AutoFile>();try{foreach(var f in plan.Files){File.Copy(Core.Inside(plan.Root,f.Path),Core.Inside(plan.Root,f.Backup),false);if(Core.Hash(Core.Inside(plan.Root,f.Backup))!=f.OriginalHash)throw new Exception("Backup verification failed");}StopIfActive(plan.Root);foreach(var f in plan.Files){if(Core.Hash(Core.Inside(plan.Root,f.Path))!=f.OriginalHash)throw new Exception("Game updated during preparation");changed.Add(f);File.WriteAllBytes(Core.Inside(plan.Root,f.Path),f.Generated);if(Core.Hash(Core.Inside(plan.Root,f.Path))!=f.PatchedHash)throw new Exception("Bridge write verification failed");log("Installed generic bridge: "+f.Path);}log("Generic bridge files verified; launch game from Steam to test.");}catch(Exception failure){var errors=new List<string>();foreach(var f in changed)try{File.Copy(Core.Inside(plan.Root,f.Backup),Core.Inside(plan.Root,f.Path),true);if(Core.Hash(Core.Inside(plan.Root,f.Path))!=f.OriginalHash)throw new Exception("Rollback checksum mismatch");}catch(Exception e){errors.Add(e.Message);}if(errors.Count>0)throw new Exception(failure.Message+"; rollback incomplete; retain backups and state: "+string.Join("; ",errors.ToArray()));log("Operation failed; game files rolled back. Use generic restore to archive retained backups.");throw;}}
 public static void Restore(string root,Action<string> log){var state=new JavaScriptSerializer().Deserialize<AutoState>(File.ReadAllText(StatePath(root)));if(state.Version!="0.3.0-test1"||state.Files==null||state.Files.Count==0)throw new Exception("Unsupported installation record");StopIfActive(root);foreach(var f in state.Files){string backup=Core.Inside(root,f.Backup),target=Core.Inside(root,f.Path);if(!File.Exists(target))throw new Exception("Target unavailable: "+f.Path);string hash=Core.Hash(target);if(File.Exists(backup)){if(Core.Hash(backup)!=f.OriginalHash)throw new Exception("Backup damaged: "+f.Path);}else if(hash!=f.OriginalHash)throw new Exception("Required original backup missing: "+f.Path);if(hash!=f.OriginalHash&&hash!=f.PatchedHash)throw new Exception("Game updated; refuse restoring an older version: "+f.Path);}var snapshots=new Dictionary<string,byte[]>();try{foreach(var f in state.Files){string path=Core.Inside(root,f.Path);snapshots[path]=File.ReadAllBytes(path);if(Core.Hash(path)!=f.OriginalHash)File.Copy(Core.Inside(root,f.Backup),path,true);if(Core.Hash(path)!=f.OriginalHash)throw new Exception("Restore checksum mismatch");log("Restored: "+f.Path);}}catch{foreach(var p in snapshots)File.WriteAllBytes(p.Key,p.Value);throw;}
 // Archive runtime originals and the record, retaining user data without blocking the next installation.
 string archive=Core.Inside(root,"LegacySteamFixer-Auto/archive-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(archive);foreach(var f in state.Files){string dest=Core.Inside(archive,f.Backup);Directory.CreateDirectory(Path.GetDirectoryName(dest));if(File.Exists(Core.Inside(root,f.Backup)))File.Move(Core.Inside(root,f.Backup),dest);}File.Move(StatePath(root),Path.Combine(archive,"state.json"));log("Generic original files restored; backups archived: "+archive);}
}
