using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Web.Script.Serialization;
using System.Diagnostics;
using Microsoft.Win32;
public class Target { public string Path,Backup,Original,Patched,Payload,PayloadHash; public bool Delta; }
public class Module { public string Id,AppId,Name,Marker,Preflight; public bool X64; public Target[] Targets; }
public class Game { public string AppId,Name,Root,Status,Detail; public Module Module; public override string ToString(){return Name;} }
public static class Core {
 public static string Base=AppDomain.CurrentDomain.BaseDirectory;
 public static Module[] Modules=new JavaScriptSerializer().Deserialize<Module[]>(File.ReadAllText(System.IO.Path.Combine(Base,"modules/catalog.json")));
 public static string Hash(string p){using(var h=SHA256.Create())using(var f=File.OpenRead(p))return BitConverter.ToString(h.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
 public static string Inside(string root,string rel){string p=System.IO.Path.GetFullPath(System.IO.Path.Combine(root,rel.Replace('/',System.IO.Path.DirectorySeparatorChar)));string prefix=System.IO.Path.GetFullPath(root).TrimEnd(new char[] {System.IO.Path.DirectorySeparatorChar})+System.IO.Path.DirectorySeparatorChar;if(!p.StartsWith(prefix,StringComparison.OrdinalIgnoreCase))throw new Exception("Path outside root");string cur=p;while(cur.Length>=prefix.Length){if((File.Exists(cur)||Directory.Exists(cur))&&(File.GetAttributes(cur)&FileAttributes.ReparsePoint)!=0)throw new Exception("Reparse point rejected: "+cur);cur=System.IO.Path.GetDirectoryName(cur);}return p;}
 public static string SteamRoot(){foreach(string k in new[]{@"HKEY_CURRENT_USER\Software\Valve\Steam",@"HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam",@"HKEY_LOCAL_MACHINE\SOFTWARE\Valve\Steam"}){object x=Registry.GetValue(k,k.Contains("CURRENT_USER")?"SteamPath":"InstallPath",null);if(x!=null&&Directory.Exists(x.ToString()))return x.ToString();}return "";}
 // Valve KeyValues: quoted/bare strings, escaped backslashes and comments.
 public static Dictionary<string,object> Vdf(string s){int i=0;return Obj(s,ref i,false);}
 static string Token(string s,ref int i){while(i<s.Length){if(char.IsWhiteSpace(s[i])){i++;continue;}if(i+1<s.Length&&s[i]=='/'&&s[i+1]=='/'){while(i<s.Length&&s[i]!='\n')i++;continue;}break;}if(i==s.Length)return null;char c=s[i++];if(c=='{'||c=='}')return c.ToString();var b=new StringBuilder();if(c=='"'){while(i<s.Length){c=s[i++];if(c=='"')return b.ToString();if(c=='\\'&&i<s.Length&&(s[i]=='\\'||s[i]=='"'))c=s[i++];b.Append(c);}throw new Exception("Unclosed VDF string");}b.Append(c);while(i<s.Length&&!char.IsWhiteSpace(s[i])&&s[i]!='{'&&s[i]!='}')b.Append(s[i++]);return b.ToString();}
 static Dictionary<string,object> Obj(string s,ref int i,bool nested){var d=new Dictionary<string,object>(StringComparer.OrdinalIgnoreCase);string k;while((k=Token(s,ref i))!=null){if(k=="}"){if(!nested)throw new Exception("Unexpected VDF brace");return d;}string v=Token(s,ref i);if(v==null||v=="}")throw new Exception("Missing VDF value");d[k]=v=="{"?(object)Obj(s,ref i,true):v;}if(nested)throw new Exception("Unclosed VDF object");return d;}
 static string S(Dictionary<string,object> d,string key){object o;return d.TryGetValue(key,out o)&&o is string?(string)o:"";}
 public static List<Game> Scan(string steam,Action<string> log){var games=new List<Game>();var libraries=new HashSet<string>(StringComparer.OrdinalIgnoreCase);libraries.Add(System.IO.Path.GetFullPath(steam));string vdf=System.IO.Path.Combine(steam,"steamapps/libraryfolders.vdf");if(File.Exists(vdf)){var d=Vdf(File.ReadAllText(vdf));object o;if(d.TryGetValue("libraryfolders",out o)&&o is Dictionary<string,object>)foreach(var pair in (Dictionary<string,object>)o){int n;if(!int.TryParse(pair.Key,out n))continue;string p=pair.Value as string;if(pair.Value is Dictionary<string,object>)p=S((Dictionary<string,object>)pair.Value,"path");if(!string.IsNullOrEmpty(p))libraries.Add(System.IO.Path.GetFullPath(p));}}
 var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(string lib in libraries){string apps=System.IO.Path.Combine(lib,"steamapps");if(!Directory.Exists(apps))continue;foreach(string f in Directory.GetFiles(apps,"appmanifest_*.acf")){try{var d=Vdf(File.ReadAllText(f));var state=(Dictionary<string,object>)d["AppState"];string dir=S(state,"installdir");if(string.IsNullOrEmpty(dir))continue;string root=Inside(System.IO.Path.Combine(apps,"common"),dir);if(!Directory.Exists(root)||!seen.Add(root))continue;var g=new Game{AppId=S(state,"appid"),Name=S(state,"name"),Root=root};Inspect(g);games.Add(g);}catch(Exception e){log(f+": "+e.Message);}}}return games;}
 public static void Inspect(Game g){g.Module=null;foreach(var m in Modules)if((g.AppId==m.AppId||string.IsNullOrEmpty(g.AppId))&&File.Exists(Inside(g.Root,m.Marker))){g.Module=m;break;}g.Detail="";if(g.Module==null){g.Status="Unsupported";return;}if(g.Module.X64&&!Environment.Is64BitOperatingSystem){g.Status="Requires64";return;}int patched=0;try{foreach(var t in g.Module.Targets){string p=Inside(g.Root,t.Path);if(!File.Exists(p))throw new Exception("Missing: "+t.Path);string hash=Hash(p);g.Detail+=t.Path+" SHA256="+hash+Environment.NewLine;if(hash==t.Patched)patched++;else if(hash!=t.Original)throw new Exception("Unknown version: "+t.Path);string saved=Inside(g.Root,t.Backup);if(File.Exists(saved)&&Hash(saved)!=t.Original)throw new Exception("Invalid backup: "+t.Backup);if(hash==t.Patched&&FindOriginal(g,t)==null)throw new Exception("Original backup missing: "+t.Path);}g.Status=patched==g.Module.Targets.Length?"Patched":"Ready";}catch(Exception e){g.Status="Mismatch";g.Detail+=e.Message;}}
 static string FindOriginal(Game g,Target t){foreach(string rel in new[]{t.Backup,"LegacySteam-Test1-Backup/"+t.Path,t.Path}){string p=Inside(g.Root,rel);if(File.Exists(p)&&Hash(p)==t.Original)return p;}return null;}
 public static void CheckProcesses(Game g){foreach(var p in Process.GetProcesses()){try{string name;try{name=p.ProcessName;}catch(InvalidOperationException){continue;}if(g.Module.Id=="gmod"&&(name=="gmod"||name=="gmod_win64"||name=="hl2"))throw new InvalidOperationException("Close Garry's Mod first.");if(name=="dotnet"||name=="tModLoader"){string exe;try{exe=p.MainModule.FileName;}catch{throw new InvalidOperationException("Cannot inspect active game process. Close dotnet/tModLoader first.");}if(exe.StartsWith(g.Root.TrimEnd(new char[] {'\\'})+"\\",StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Close tModLoader first.");}}finally{p.Dispose();}}}
 public static void Apply(Game g,bool restore,Action<string> log){Inspect(g);if(g.Status!="Ready"&&g.Status!="Patched")throw new Exception(g.Status+": "+g.Detail);CheckProcesses(g);string mod=Inside(Base,"modules/"+g.Module.Id);if(!restore&&g.Module.Id=="tml")Preflight(g,mod,log);
 string stage=Inside(g.Root,"LegacySteamFixer-Stage-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(stage);var changed=new List<Target>();bool finished=false;
 try{foreach(var t in g.Module.Targets){string current=Inside(g.Root,t.Path),original=FindOriginal(g,t);if(original==null)throw new Exception("Original missing: "+t.Path);string saved=Inside(g.Root,t.Backup);if(!File.Exists(saved)){Directory.CreateDirectory(System.IO.Path.GetDirectoryName(saved));File.Copy(original,saved,false);}if(Hash(saved)!=t.Original)throw new Exception("Backup validation failed");string output=Inside(stage,"new/"+t.Path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(output));if(restore)File.Copy(saved,output);else{string payload=Inside(mod,t.Payload);if(Hash(payload)!=t.PayloadHash)throw new Exception("Damaged patch payload");byte[] result=t.Delta?LegacyDeltaPatch.Apply(File.ReadAllBytes(saved),File.ReadAllBytes(payload)):File.ReadAllBytes(payload);File.WriteAllBytes(output,result);}if(Hash(output)!=(restore?t.Original:t.Patched))throw new Exception("Output validation failed");string rollback=Inside(stage,"old/"+t.Path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(rollback));File.Copy(current,rollback);}
 // Recheck every input after staging, before first replacement.
 foreach(var t in g.Module.Targets)if(Hash(Inside(g.Root,t.Path))!=Hash(Inside(stage,"old/"+t.Path)))throw new Exception("Game files changed while preparing");CheckProcesses(g);
 try{foreach(var t in g.Module.Targets){changed.Add(t);File.Copy(Inside(stage,"new/"+t.Path),Inside(g.Root,t.Path),true);if(Hash(Inside(g.Root,t.Path))!=(restore?t.Original:t.Patched))throw new Exception("Write verification failed");log(t.Path);}}catch(Exception failure){var errors=new List<string>();foreach(var t in changed)try{File.Copy(Inside(stage,"old/"+t.Path),Inside(g.Root,t.Path),true);if(Hash(Inside(g.Root,t.Path))!=Hash(Inside(stage,"old/"+t.Path)))throw new Exception("rollback hash mismatch");}catch(Exception e){errors.Add(e.Message);}if(errors.Count>0)throw new Exception(failure.Message+"; rollback incomplete. Retained recovery files: "+stage+"; "+string.Join("; ",errors.ToArray()));throw;}
 finished=true;log(restore?"RESTORED":"PATCH FILES VERIFIED; launch game to test.");}finally{if(finished||changed.Count==0)Directory.Delete(stage,true);}Inspect(g);}
 static void Preflight(Game g,string mod,Action<string> log){string ps=System.IO.Path.Combine(Environment.GetEnvironmentVariable("SystemRoot"),Environment.Is64BitProcess?@"System32\WindowsPowerShell\v1.0\powershell.exe":@"Sysnative\WindowsPowerShell\v1.0\powershell.exe");var si=new ProcessStartInfo(ps,"-NoProfile -ExecutionPolicy Bypass -File \""+Inside(mod,g.Module.Preflight)+"\" -Root \""+g.Root.TrimEnd(new char[] {'\\'})+"\"");si.UseShellExecute=false;si.CreateNoWindow=true;si.RedirectStandardOutput=true;si.RedirectStandardError=true;using(var p=Process.Start(si)){string err="";p.ErrorDataReceived+=(s,e)=>{if(e.Data!=null)err+=e.Data+"\n";};p.BeginErrorReadLine();string output=p.StandardOutput.ReadToEnd();p.WaitForExit();log(output);if(p.ExitCode!=0)throw new Exception("Steam interface preflight failed: "+output+err);}}
}
