using System;using System.IO;using System.Text;using System.Diagnostics;using System.Collections.Generic;using System.Web.Script.Serialization;using System.Security.Cryptography;
public class LaunchProfile {public string Version="0.4.0-test1",Id,Name,Root,Exe,Steam,AppId,Mode,Api,ApiHash,ClientHash,Arguments;public bool Overlay;}
public static class LaunchProfiles {
 public static string InjectorHash="07ca91057dcd36dbbc5b9401506600f5daf6d75d4907a6352e1d8aae6821ebba",BridgeHash="e314a78e9a56ea96ffd3a4628f5d279e71cff22fb37fa8135795b5d28d9163b3";
 public static string Folder{get{return Core.Inside(Core.Base,"profiles");}}
 public static string Id(string root,string exe){using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(Encoding.UTF8.GetBytes(Path.GetFullPath(root).ToLowerInvariant()+"|"+Path.GetFullPath(exe).ToLowerInvariant()))).Replace("-","").ToLowerInvariant();}
 public static void ValidateId(string id){if(id==null||id.Length!=64)throw new Exception("Invalid profile ID");foreach(char c in id)if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))throw new Exception("Invalid profile ID");}
 public static string JsonPath(string id){ValidateId(id);return Core.Inside(Folder,id+".json");}
 public static string ConfigPath(LaunchProfile p){ValidateId(p.Id);return Core.Inside(Folder,p.Id+"/launch.txt");}
 public static LaunchProfile Load(string id){ValidateId(id);var p=new JavaScriptSerializer().Deserialize<LaunchProfile>(File.ReadAllText(JsonPath(id)));if(p==null||p.Version!="0.4.0-test1"||p.Id!=id||p.Id!=Id(p.Root,p.Exe))throw new Exception("Invalid saved profile");ValidatePaths(p);return p;}
 public static LaunchProfile Last(){string path=Core.Inside(Folder,"last.txt");if(!File.Exists(path))return null;return Load(File.ReadAllText(path).Trim());}
 public static void ValidatePaths(LaunchProfile p){if(p.Mode!="inject"&&p.Mode!="generic"&&p.Mode!="module")throw new Exception("Unsupported profile mode");string exe=Core.Inside(p.Root,p.Exe);if(!File.Exists(exe))throw new Exception("Selected game executable missing");uint id;if(!uint.TryParse(p.AppId,out id)||id==0)throw new Exception("Installed Steam AppID not resolved");if(p.Mode=="inject")Core.Inside(p.Root,p.Api);}
 public static void Save(LaunchProfile p){ValidatePaths(p);p.Id=Id(p.Root,p.Exe);Directory.CreateDirectory(Folder);Atomic(JsonPath(p.Id),new JavaScriptSerializer().Serialize(p));Atomic(Core.Inside(Folder,"last.txt"),p.Id);}
 static void Atomic(string path,string text){string temp=path+".tmp-"+Guid.NewGuid().ToString("N");try{File.WriteAllText(temp,text,Encoding.UTF8);if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}finally{if(File.Exists(temp))File.Delete(temp);}}
 public static AutoFile SelectInjectionFile(string exe,AutoPlan plan){string normalized=exe.Replace('\\','/');int slash=normalized.LastIndexOf('/');string dir=slash<0?"":normalized.Substring(0,slash+1);string expected=dir+Path.GetFileNameWithoutExtension(normalized)+"_Data/Plugins/x86_64/steam_api64.dll";var matches=new List<AutoFile>();foreach(var f in plan.Files)if(f.Path.Replace('\\','/').Equals(expected,StringComparison.OrdinalIgnoreCase))matches.Add(f);if(matches.Count==1)return matches[0];if(matches.Count>1||plan.Files.Count!=1)throw new Exception("Cannot uniquely match the selected executable to its SteamAPI; select the correct game executable");return plan.Files[0];}
 public static string ValidateInjectionPlan(Game game,string exe,AutoPlan plan){if(!Environment.Is64BitOperatingSystem)throw new Exception("Injection requires 64-bit Windows");if(plan==null||plan.Files.Count==0)throw new Exception("Injection requires a supported native x64 SteamAPI");AutoFile selected=SelectInjectionFile(exe,plan);string exePath=Core.Inside(game.Root,exe);byte[] head=new byte[4096];using(var f=File.OpenRead(exePath)){int n=f.Read(head,0,head.Length);if(n<64||BitConverter.ToUInt16(head,0)!=0x5a4d)throw new Exception("Game executable is not PE");int pe=BitConverter.ToInt32(head,0x3c);if(pe<0||pe>n-24||BitConverter.ToUInt32(head,pe)!=0x4550||BitConverter.ToUInt16(head,pe+4)!=0x8664)throw new Exception("Injection supports native x64 game executables only");int opt=pe+24;if(opt+232>n||BitConverter.ToUInt16(head,opt)!=0x20b||BitConverter.ToUInt32(head,opt+224)!=0)throw new Exception("Injection does not support managed game executables");}
 string api=Core.Inside(game.Root,selected.Path);var image=new PeImage(File.ReadAllBytes(api));foreach(string name in new[]{"SteamInternal_SteamAPI_Init","SteamInternal_CreateInterface","SteamAPI_InitFlat","SteamAPI_InitSafe"}){var e=image.Find(name);if(e==null||e.Address==0||image.IsForwarder(e))throw new Exception("Injection entry unsupported: "+name);}return selected.Path;}
 public static void Remove(LaunchProfile p){if(p==null)return;if(File.Exists(JsonPath(p.Id)))File.Delete(JsonPath(p.Id));string last=Core.Inside(Folder,"last.txt");if(File.Exists(last)&&File.ReadAllText(last).Trim()==p.Id)File.Delete(last);}
 public static void CheckIdle(Game game){foreach(var proc in Process.GetProcesses())using(proc){try{string file=proc.MainModule.FileName;if(file.StartsWith(Path.GetFullPath(game.Root).TrimEnd('\\','/')+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Close game-folder processes first: "+proc.ProcessName);}catch(System.ComponentModel.Win32Exception){}catch(NotSupportedException){}catch(InvalidOperationException e){if(e.Message.StartsWith("Close game-folder"))throw;}}}
 public static void ValidateForLaunch(LaunchProfile p){ValidatePaths(p);if(!Directory.Exists(p.Steam)||!File.Exists(Core.Inside(p.Steam,"steam.exe")))throw new Exception("Steam installation unavailable");
 bool manifest=false;foreach(var g in Core.Scan(p.Steam,x=>{}))if(Path.GetFullPath(g.Root).TrimEnd('\\','/').Equals(Path.GetFullPath(p.Root).TrimEnd('\\','/'),StringComparison.OrdinalIgnoreCase)&&g.AppId==p.AppId)manifest=true;
 if(!manifest)throw new Exception("Installed manifest no longer matches this profile; recheck compatibility");
 var game=new Game{Root=p.Root,AppId=p.AppId,Name=p.Name};CheckIdle(game);
 if(p.Mode=="inject"){
 if(AutoBridge.HasState(p.Root))throw new Exception("Restore the installed generic bridge before injection");
 if(Core.Hash(Core.Inside(p.Root,p.Api))!=p.ApiHash)throw new Exception("Game SDK changed; recheck compatibility");
 if(Core.Hash(Core.Inside(p.Steam,"steamclient64.dll"))!=p.ClientHash)throw new Exception("Steam client changed; recheck compatibility");
 if(Core.Hash(Core.Inside(Core.Base,"inject/LegacySteam-Injector.exe"))!=InjectorHash||Core.Hash(Core.Inside(Core.Base,"inject/LegacySteam-InjectBridge.dll"))!=BridgeHash)throw new Exception("Injection component checksum mismatch");
 if(!Path.GetFullPath(Core.SteamRoot()).TrimEnd('\\','/').Equals(Path.GetFullPath(p.Steam).TrimEnd('\\','/'),StringComparison.OrdinalIgnoreCase))throw new Exception("Configured Steam differs from registry Steam installation");
 }else if(p.Mode=="module"){Core.Inspect(game);if(game.Status!="Patched")throw new Exception("Dedicated repair files changed; recheck compatibility");}
 else{string state=Core.Inside(p.Root,"LegacySteamFixer-Auto/state.json");var recorded=new JavaScriptSerializer().Deserialize<AutoState>(File.ReadAllText(state));if(recorded==null||recorded.Version!="0.3.0-test1"||recorded.Files==null||recorded.Files.Count==0)throw new Exception("Generic bridge record invalid");foreach(var f in recorded.Files)if(Core.Hash(Core.Inside(p.Root,f.Path))!=f.PatchedHash)throw new Exception("Generic bridge files changed; recheck compatibility");}
 }
 public static void Launch(LaunchProfile p,Action<string> log){ValidateForLaunch(p);if(p.Mode!="inject"){Process.Start(new ProcessStartInfo(Core.Inside(p.Steam,"steam.exe"),"-applaunch "+p.AppId){UseShellExecute=false});log("Launch request sent to Steam; verify actual gameplay.");return;}
 string exe=Core.Inside(p.Root,p.Exe),api=Core.Inside(p.Root,p.Api);string cfg=ConfigPath(p);if(cfg.Length>=230||Core.Base.Length>=220)throw new Exception("Move the tool to a shorter writable path before injection");Directory.CreateDirectory(Path.GetDirectoryName(cfg));foreach(string field in new[]{exe,p.Root,api,p.AppId})if(field.Length>=240||field.Contains("\r")||field.Contains("\n"))throw new Exception("Unsupported long path or newline in injection configuration");
 LaunchOptions.Validate(p.Arguments);string renderer=p.Overlay?Core.Inside(p.Steam,"GameOverlayRenderer64.dll"):"";if(p.Overlay&&!File.Exists(renderer))throw new Exception("Steam overlay renderer is missing: "+renderer);if(renderer.Length>=240)throw new Exception("Steam overlay path is too long");File.WriteAllText(cfg,exe+"\r\n"+p.Root+"\r\n"+api+"\r\n"+p.AppId+"\r\n"+(p.Arguments??"")+"\r\n"+renderer+"\r\n",Encoding.Unicode);
 string helper=Core.Inside(Core.Base,"inject/LegacySteam-Injector.exe");using(var proc=Process.Start(new ProcessStartInfo(helper,"\""+cfg+"\""){UseShellExecute=false,WorkingDirectory=Core.Base})){if(!proc.WaitForExit(60000))throw new Exception("Injector still running; inspect injector log before retrying");if(proc.ExitCode!=0)throw new Exception("Injector failed, code "+proc.ExitCode+"; log: "+Path.Combine(Path.GetDirectoryName(cfg),"LegacySteam-Injector.log"));}
 if(Core.Hash(api)!=p.ApiHash)throw new Exception("Game SDK disk hash changed during launch");log("Injection bootstrap succeeded. Original SDK disk hash unchanged; verify gameplay.");log(Path.Combine(Path.GetDirectoryName(cfg),"LegacySteam-Injector.log"));
 }
}
