using System;using System.IO;using System.Drawing;using System.Windows.Forms;using System.Collections.Generic;using System.ComponentModel;using System.Globalization;using System.Text;
class RepairContext {public Game Game;public string Exe,Api,Error;public AnalysisReport Report;public AutoPlan Plan;}
class MainForm:ThemedForm {
 int lang;bool busy;string steam=Core.SteamRoot();List<Game> games=new List<Game>();Dictionary<string,LaunchProfile> profiles=new Dictionary<string,LaunchProfile>(StringComparer.OrdinalIgnoreCase);Dictionary<string,RepairContext> contexts=new Dictionary<string,RepairContext>(StringComparer.OrdinalIgnoreCase);
 TextBox steamPath=new TextBox(),filter=new TextBox(),log=new TextBox();ListView list=new ListView();Label help=new Label(),status=new Label();Button scan=new StyledButton(),manage=new StyledButton(),repair=new StyledButton(),launch=new StyledButton(),restore=new StyledButton(),zstd=new StyledButton();
 string T(string en,string cn,string tw){return lang==1?cn:lang==2?tw:en;}
 public MainForm(){string culture=CultureInfo.CurrentUICulture.Name.ToLowerInvariant();lang=culture.StartsWith("zh")?(culture.Contains("tw")||culture.Contains("hk")||culture.Contains("hant")?2:1):0;
 Text=AppInfo.DisplayName;ClientSize=new Size(1000,720);MinimumSize=new Size(900,680);Font=new Font("Microsoft YaHei",9);BackColor=UiTheme.Background;ForeColor=UiTheme.Text;
 var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(20,4,20,14),ColumnCount=1,RowCount=7};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,44));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,38));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,60));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,52));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,32));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,142));var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Margin=new Padding(0)};shell.RowStyles.Add(new RowStyle(SizeType.Absolute,64));shell.RowStyles.Add(new RowStyle(SizeType.Percent,100));Controls.Add(shell);var heading=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(23,8,23,0),ColumnCount=2,RowCount=2};heading.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));heading.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,135));heading.RowStyles.Add(new RowStyle(SizeType.Absolute,30));heading.RowStyles.Add(new RowStyle(SizeType.Percent,100));heading.Controls.Add(new Label{Text="LegacySteamFixer",Dock=DockStyle.Fill,Font=new Font(Font.FontFamily,16,FontStyle.Bold),ForeColor=UiTheme.Text},0,0);heading.Controls.Add(new Label{Text=T("Your games, with legacy Steam compatibility","游戏库与旧版 Steam 兼容修补","遊戲庫與舊版 Steam 相容修補"),Dock=DockStyle.Fill,ForeColor=UiTheme.Muted},0,1);heading.Controls.Add(new Label{Text=AppInfo.Version,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,ForeColor=UiTheme.Muted},1,0);shell.Controls.Add(heading,0,0);shell.Controls.Add(layout,0,1);layout.Margin=new Padding(0);
 var top=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1,Margin=new Padding(0)};top.RowStyles.Add(new RowStyle(SizeType.Percent,100));top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));top.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,150));top.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,150));top.Controls.Add(new Label{Text=T("Game library","游戏库","遊戲庫"),Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,Font=new Font(Font,FontStyle.Bold)},0,0);Setup(scan,T("Refresh games","刷新游戏列表","重新整理遊戲列表"),()=>Scan());top.Controls.Add(scan,1,0);Setup(manage,T("Diagnostics","诊断 / 日志","診斷 / 日誌"),()=>Manage());top.Controls.Add(manage,2,0);layout.Controls.Add(top,0,0);
 var find=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=new Padding(0)};find.RowStyles.Add(new RowStyle(SizeType.Percent,100));find.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,85));find.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));find.Controls.Add(new Label{Text=T("Filter games","筛选游戏","篩選遊戲"),Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,0);filter.BorderStyle=BorderStyle.FixedSingle;filter.BackColor=Color.White;filter.Dock=DockStyle.Fill;filter.TextChanged+=(s,e)=>RefreshList(null);find.Controls.Add(UiTheme.Input(filter),1,0);layout.Controls.Add(find,0,1);
 list.Dock=DockStyle.Fill;list.View=View.Details;list.FullRowSelect=true;list.MultiSelect=false;list.HideSelection=false;list.Columns.Add(T("Game","游戏","遊戲"),210);list.Columns.Add(T("Compatibility status","兼容状态","相容狀態"),180);list.Columns.Add(T("Launch method","启动方式","啟動方式"),150);list.Columns.Add("AppID",90);list.Columns.Add(T("Folder","目录","目錄"),330);list.ShowItemToolTips=true;list.SizeChanged+=(s,e)=>FitColumns();list.ColumnWidthChanging+=(s,e)=>{e.Cancel=true;e.NewWidth=list.Columns[e.ColumnIndex].Width;};list.SelectedIndexChanged+=(s,e)=>UpdateState();UiTheme.StyleList(list);var rows=new ImageList();rows.ImageSize=new Size(1,32);list.SmallImageList=rows;list.Disposed+=(s,e)=>rows.Dispose();layout.Controls.Add(UiTheme.Card(list),0,2);
 help.ForeColor=UiTheme.Muted;help.Dock=DockStyle.Fill;help.TextAlign=ContentAlignment.MiddleLeft;layout.Controls.Add(help,0,3);
 var bar=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1,Margin=new Padding(0)};bar.RowStyles.Add(new RowStyle(SizeType.Percent,100));foreach(float width in new[]{34f,40f,26f})bar.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,width));Setup(repair,T("Patch","修补","修補"),()=>Repair());Setup(launch,T("Launch game","启动游戏","啟動遊戲"),()=>Launch());Setup(restore,T("Restore","还原","還原"),()=>Restore());Setup(zstd,T("Enable Zstd downloads","启用 Zstd 下载补丁","啟用 Zstd 下載補丁"),()=>EnableZstd());((StyledButton)launch).Primary=true;Button[] actions={repair,launch,restore};for(int i=0;i<actions.Length;i++)bar.Controls.Add(actions[i],i,0);layout.Controls.Add(bar,0,4);
 var steamTools=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=3,Padding=new Padding(12,8,12,8),BackColor=Color.White,Margin=new Padding(3,6,3,0)};steamTools.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));steamTools.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,165));steamTools.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,205));steamTools.RowStyles.Add(new RowStyle(SizeType.Absolute,28));steamTools.RowStyles.Add(new RowStyle(SizeType.Absolute,42));steamTools.RowStyles.Add(new RowStyle(SizeType.Percent,100));var steamTitle=new Label{Text=T("Steam tools","Steam 工具","Steam 工具"),Dock=DockStyle.Fill,Font=new Font(Font,FontStyle.Bold),TextAlign=ContentAlignment.MiddleLeft};steamTools.Controls.Add(steamTitle,0,0);steamTools.SetColumnSpan(steamTitle,3);steamPath.ReadOnly=true;steamPath.Text=steam;steamPath.ForeColor=UiTheme.Muted;steamTools.Controls.Add(UiTheme.Input(steamPath),0,1);var chooseSteam=new StyledButton();Setup(chooseSteam,T("Choose Steam folder","选择 Steam 目录","選擇 Steam 目錄"),()=>{using(var f=new FolderBrowserDialog())if(f.ShowDialog(this)==DialogResult.OK){steam=f.SelectedPath;steamPath.Text=steam;Scan();}});steamTools.Controls.Add(chooseSteam,1,1);steamTools.Controls.Add(zstd,2,1);var download=new StyledButton();Setup(download,T("Download Steam installer","下载 Steam 安装器","下載 Steam 安裝程式"),()=>System.Diagnostics.Process.Start("https://store.steampowered.com/about/"));steamTools.Controls.Add(download,2,2);var note=new Label{Text=T("Official installer for Windows 7/8.1; verify client 1730853000. Zstd validates the exact client hash.","官网安装器用于 Win7/8.1；需核对客户端 1730853000。Zstd 会校验指定客户端文件。","官網安裝程式用於 Win7/8.1；須核對用戶端 1730853000。Zstd 會校驗指定用戶端檔案。"),Dock=DockStyle.Fill,ForeColor=UiTheme.Muted,TextAlign=ContentAlignment.MiddleLeft};steamTools.Controls.Add(note,0,2);steamTools.SetColumnSpan(note,2);layout.Controls.Add(steamTools,0,6);scan.EnabledChanged+=(s,e)=>{chooseSteam.Enabled=download.Enabled=scan.Enabled;};
 status.ForeColor=UiTheme.Muted;status.Dock=DockStyle.Fill;status.AutoEllipsis=true;layout.Controls.Add(status,0,5);log.Multiline=true;log.ReadOnly=true;log.ScrollBars=ScrollBars.Both;Shown+=(s,e)=>Scan();FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};UpdateState();}
 void FitColumns(){if(list.Columns.Count!=5)return;int width=Math.Max(1,list.ClientSize.Width-2-SystemInformation.VerticalScrollBarWidth);double[] weights={.25,.22,.18,.10,.25};int used=0;for(int i=0;i<4;i++){int size=(int)(width*weights[i]);list.Columns[i].Width=size;used+=size;}list.Columns[4].Width=Math.Max(1,width-used);}
 void Setup(Button b,string text,Action action){b.Text=text;b.Dock=DockStyle.Fill;b.Height=38;b.Font=new Font(Font.FontFamily,9,FontStyle.Regular);b.Margin=new Padding(3,4,6,4);b.Click+=(s,e)=>action();}
 Game Selected(){return list.SelectedItems.Count==0?null:(Game)list.SelectedItems[0].Tag;}
 LaunchProfile Profile(Game g){LaunchProfile p;return g!=null&&profiles.TryGetValue(g.Root,out p)?p:null;}
 void ReadProfiles(){profiles.Clear();if(!Directory.Exists(LaunchProfiles.Folder))return;var files=new List<string>(Directory.GetFiles(LaunchProfiles.Folder,"*.json"));files.Sort((a,b)=>File.GetLastWriteTimeUtc(a).CompareTo(File.GetLastWriteTimeUtc(b)));foreach(string path in files)try{var p=LaunchProfiles.Load(Path.GetFileNameWithoutExtension(path));profiles[p.Root]=p;}catch(Exception e){Log("Saved profile: "+e.Message);}}
 string RowStatus(Game g){if(AutoBridge.HasState(g.Root))return T("Replacement bridge installed","已安装替换桥接","已安裝替換橋接");var p=Profile(g);if(p!=null)return p.Mode=="inject"?T("Injection configured","已配置注入启动","已設定注入啟動"):T("Repair configured","已配置修补","已設定修補");if(g.Status=="Patched")return T("Dedicated repair installed","已安装专用修补","已安裝專用修補");if(g.Status=="Ready")return T("Dedicated repair available","可使用专用修补","可使用專用修補");if(g.Status=="Mismatch")return T("Version / backup needs checking","版本或备份待检查","版本或備份待檢查");return T("Not checked","尚未检查","尚未檢查");}
 string Mode(LaunchProfile p){if(p==null)return T("Normal Steam launch","普通 Steam 启动","一般 Steam 啟動");return p.Mode=="inject"?T("Memory injection","内存注入","記憶體注入"):p.Mode=="module"?T("Dedicated repair","专用修补","專用修補"):T("DLL replacement","DLL 替换桥接","DLL 替換橋接");}
 void RefreshList(string preferred){if(busy)return;Game old=Selected();string selected=preferred??(old==null?null:old.Root);list.BeginUpdate();list.Items.Clear();foreach(var g in games){string q=filter.Text.Trim();if(q!=""&&g.Name.IndexOf(q,StringComparison.OrdinalIgnoreCase)<0&&g.AppId.IndexOf(q,StringComparison.OrdinalIgnoreCase)<0)continue;var row=new ListViewItem(new[]{g.Name,RowStatus(g),Mode(Profile(g)),g.AppId,g.Root});row.Tag=g;row.ToolTipText=g.Name+"\n"+g.Root;list.Items.Add(row);if(selected!=null&&g.Root.Equals(selected,StringComparison.OrdinalIgnoreCase)){row.Selected=true;row.Focused=true;}}list.EndUpdate();UpdateState();}
 void UpdateState(){Game g=Selected();bool selected=g!=null&&!busy;scan.Enabled=manage.Enabled=filter.Enabled=!busy;list.Enabled=!busy;repair.Enabled=launch.Enabled=selected;restore.Enabled=selected&&(AutoBridge.HasState(g.Root)||Profile(g)!=null||g.Status=="Patched");zstd.Enabled=!busy;
 repair.Text=g!=null&&AutoBridge.HasState(g.Root)?T("Restore and repatch","还原并修补","還原並修補"):T("Patch","修补","修補");
 help.Text=g==null?T("Select a game above, then Patch or Launch game. Steam tools are in the separate area below.","在上方选择游戏，再点击“修补”或“启动游戏”。Steam 相关操作位于下方独立区域。","在上方選擇遊戲，再點擊「修補」或「啟動遊戲」。Steam 相關操作位於下方獨立區域。"):g.Name+" — "+Mode(Profile(g))+"\n"+T("Patch automatically checks interfaces, then lets you choose a method. Saved injection configuration is used when launching.","“修补”会自动检查接口，然后让你选择方式；已保存的注入配置会在启动时使用。","「修補」會自動檢查介面，然後讓你選擇方式；已儲存的注入設定會在啟動時使用。");}
 void Scan(){string keep=Selected()==null?null:Selected().Root;Run(()=>{if(string.IsNullOrEmpty(steam)||!Directory.Exists(steam))throw new Exception(T("Set a valid Steam folder in Diagnostics / logs.","请在下方“Steam 工具”中选择有效的 Steam 目录。","請在「診斷 / 日誌」中選擇有效的 Steam 目錄。"));games=Core.Scan(steam,Log);games.Sort((a,b)=>StringComparer.CurrentCultureIgnoreCase.Compare(a.Name,b.Name));ReadProfiles();},()=>{RefreshList(keep);status.Text=T("Installed games: ","已安装游戏：","已安裝遊戲：")+games.Count;});}
 string ChooseExe(Game g){var saved=Profile(g);if(saved!=null&&File.Exists(Core.Inside(g.Root,saved.Exe)))return saved.Exe;string exact=Path.Combine(g.Root,Path.GetFileName(g.Root)+".exe");if(File.Exists(exact))return Path.GetFileName(exact);if(g.Module!=null&&g.Module.Marker.EndsWith(".exe",StringComparison.OrdinalIgnoreCase)&&File.Exists(Core.Inside(g.Root,g.Module.Marker)))return g.Module.Marker;
 var choices=new List<string>();foreach(string p in Directory.GetFiles(g.Root,"*.exe")){string name=Path.GetFileName(p).ToLowerInvariant();if(!name.Contains("crash")&&!name.Contains("unins")&&!name.StartsWith("legacy")&&!name.StartsWith("unity"))choices.Add(p);}if(choices.Count==1)return Path.GetFileName(choices[0]);
 using(var d=new OpenFileDialog{Filter=T("Game executable (*.exe)|*.exe","游戏程序 (*.exe)|*.exe","遊戲程式 (*.exe)|*.exe"),InitialDirectory=g.Root,Title=T("Select this game's main executable","选择该游戏的主程序","選擇該遊戲的主程式")}){if(d.ShowDialog(this)!=DialogResult.OK)return null;string prefix=Path.GetFullPath(g.Root).TrimEnd('\\','/')+Path.DirectorySeparatorChar;if(!d.FileName.StartsWith(prefix,StringComparison.OrdinalIgnoreCase))throw new Exception(T("Choose an executable inside the selected game folder.","请选择所选游戏目录内的程序。","請選擇所選遊戲目錄內的程式。"));return d.FileName.Substring(prefix.Length);}}
 void Repair(){Game g=Selected();if(g==null)return;string exe;try{exe=ChooseExe(g);}catch(Exception e){UiDialogs.Error(this,e.Message,Text,T("Close","关闭","關閉"));return;}if(exe==null)return;var ctx=new RepairContext{Game=g,Exe=exe,Api="",Error=""};
 Run(()=>{LaunchProfiles.CheckIdle(g);if(AutoBridge.HasState(g.Root)){AutoBridge.Restore(g.Root,Log);var old=Profile(g);if(old!=null){LaunchProfiles.Remove(old);profiles.Remove(g.Root);}}
 Core.Inspect(g);ctx.Report=Analyzer.Analyze(g,steam,Log);try{ctx.Plan=AutoBridge.Plan(g,ctx.Report);ctx.Api=LaunchProfiles.ValidateInjectionPlan(g,exe,ctx.Plan);}catch(Exception e){ctx.Error=e.Message;Log("Plan: "+e.Message);}contexts[g.Root]=ctx;
 bool module=g.Module!=null&&(g.Status=="Ready"||g.Status=="Patched");if(ctx.Plan==null&&!module)throw new Exception(T("No supported patch plan. Details are available in Diagnostics / logs.","没有找到受支持的修补方案，可在“诊断 / 日志”中查看详情。","沒有找到受支援的修補方案，可在「診斷 / 日誌」中查看詳情。")+"\n"+ctx.Error);
 },()=>{RefreshList(g.Root);ChooseMethod(ctx);});}
 void ChooseMethod(RepairContext ctx){using(var d=new ThemedForm{Text=T("Patch selected game","修补所选游戏","修補所選遊戲"),ClientSize=new Size(700,340),StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font,BackColor=UiTheme.Background,ForeColor=UiTheme.Text}){
 var l=UiDialogs.Layout(4);l.RowStyles.Add(new RowStyle(SizeType.Absolute,76));l.RowStyles.Add(new RowStyle(SizeType.Absolute,84));l.RowStyles.Add(new RowStyle(SizeType.Absolute,84));l.RowStyles.Add(new RowStyle(SizeType.Percent,100));d.Controls.Add(l);
 l.Controls.Add(new Label{Dock=DockStyle.Fill,Text=ctx.Game.Name+"\n"+T("Choose a method, then save the patch. Then click Launch game in the main window.","第 1 步：选择方式并保存。第 2 步：回主界面点击“启动游戏”。","選擇修補方式並儲存，隨後在主介面點擊「啟動遊戲」。")},0,0);
 var inj=new RadioButton{Dock=DockStyle.Fill,Padding=new Padding(8),Margin=new Padding(0,4,0,4),BackColor=Color.White,Enabled=ctx.Api!="",Text=T("Injection launch (keep original files)\nSave configuration, then launch through this tool.","注入启动（保留原文件）\n保存启动配置后，需要从本工具启动游戏。","注入啟動（保留原檔案）\n儲存啟動設定後，須從本工具啟動遊戲。")};var rep=new RadioButton{Dock=DockStyle.Fill,Padding=new Padding(8),Margin=new Padding(0,4,0,4),BackColor=Color.White,Enabled=ctx.Plan!=null||(ctx.Game.Module!=null&&(ctx.Game.Status=="Ready"||ctx.Game.Status=="Patched")),Text=ctx.Game.Module!=null?T("Dedicated patch: use the existing game module","专用修补\n安装游戏适配模块；保留备份以便还原。","專用修補：使用現有遊戲適配模組"):T("DLL replacement: install with backup and restore support","DLL 替换桥接\n先备份再替换；检查文件的游戏可能拒绝启动。","DLL 替換橋接：備份後安裝，支援還原")};
 bool preferred=inj.Enabled&&ctx.Game.Name.IndexOf("Dancing Line",StringComparison.OrdinalIgnoreCase)>=0;inj.Checked=preferred||!rep.Enabled;rep.Checked=!inj.Checked;l.Controls.Add(inj,0,1);l.Controls.Add(rep,0,2);Button ok,cancel;var bar=UiDialogs.Buttons(T("Cancel","取消","取消"),T("Save patch","保存修补","儲存修補"),out ok,out cancel);l.Controls.Add(bar,0,3);d.AcceptButton=ok;d.CancelButton=cancel;if(d.ShowDialog(this)!=DialogResult.OK)return;bool useInject=inj.Checked;
 Run(()=>{LaunchProfiles.CheckIdle(ctx.Game);var p=new LaunchProfile{Name=ctx.Game.Name,Root=ctx.Game.Root,Exe=ctx.Exe,Steam=steam,AppId=ctx.Game.AppId};if(useInject){if(ctx.Plan==null||ctx.Api=="")throw new Exception("Injection plan unavailable");p.Mode="inject";p.Api=ctx.Api;p.ApiHash=LaunchProfiles.SelectInjectionFile(ctx.Exe,ctx.Plan).OriginalHash;p.ClientHash=ctx.Plan.ClientHash;if(Core.Hash(Core.Inside(p.Root,p.Api))!=p.ApiHash)throw new Exception("Game changed after analysis");}
 else if(ctx.Game.Module!=null&&(ctx.Game.Status=="Ready"||ctx.Game.Status=="Patched")){Core.Apply(ctx.Game,false,Log);p.Mode="module";}else{AutoBridge.Install(ctx.Plan,Log);p.Mode="generic";}LaunchProfiles.Save(p);profiles[p.Root]=p;Core.Inspect(ctx.Game);},()=>{RefreshList(ctx.Game.Root);status.Text=T("Patch/configuration saved. Click Launch game to test.","修补 / 注入配置已保存，点击“启动游戏”测试。","修補 / 注入設定已儲存，點擊「啟動遊戲」測試。");});}}
 void Launch(){Game g=Selected();if(g==null)return;var p=Profile(g);Run(()=>{if(p!=null)LaunchProfiles.Launch(p,Log);else{uint id;if(!uint.TryParse(g.AppId,out id)||id==0)throw new Exception("Installed AppID unavailable");System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Core.Inside(steam,"steam.exe"),"-applaunch "+g.AppId){UseShellExecute=false});Log("Normal Steam launch requested; no saved injection configuration was used.");}},()=>status.Text=T("Launch requested; verify actual gameplay.","已发起启动，请验证实际游戏运行。","已發起啟動，請驗證實際遊戲執行。"));}
 void Restore(){Game g=Selected();if(g==null)return;Run(()=>{LaunchProfiles.CheckIdle(g);if(AutoBridge.HasState(g.Root))AutoBridge.Restore(g.Root,Log);else{Core.Inspect(g);if(g.Module!=null&&g.Status=="Patched")Core.Apply(g,true,Log);}if(Directory.Exists(LaunchProfiles.Folder))foreach(string file in Directory.GetFiles(LaunchProfiles.Folder,"*.json")){LaunchProfile saved;try{saved=LaunchProfiles.Load(Path.GetFileNameWithoutExtension(file));}catch(Exception e){Log("Saved profile retained: "+e.Message);continue;}if(saved.Root.Equals(g.Root,StringComparison.OrdinalIgnoreCase))LaunchProfiles.Remove(saved);}profiles.Remove(g.Root);Core.Inspect(g);contexts.Remove(g.Root);},()=>{RefreshList(g.Root);status.Text=T("Patch restored / launch setup removed; original files retained.","已还原修补 / 移除启动配置，保留原文件。","已還原修補 / 移除啟動設定，保留原檔案。");});}
 void EnableZstd(){using(var d=new ThemedForm{Text=T("Zstd download support","Zstd 下载补丁","Zstd 下載補丁"),ClientSize=new Size(660,300),StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font,BackColor=UiTheme.Background,ForeColor=UiTheme.Text}){var l=UiDialogs.Layout(2);l.RowStyles.Add(new RowStyle(SizeType.Percent,100));l.RowStyles.Add(new RowStyle(SizeType.Absolute,52));l.Controls.Add(new Label{Dock=DockStyle.Fill,Margin=new Padding(0),Text=T("Enable Zstd decompression for the supported Steam client.\n\n1. Pause downloads and close games.\n2. Click Enable and accept the Windows administrator prompt.\n3. Resume downloads after the helper reports success.\n\nSteam starts automatically if needed. Reapply after Steam exits or restarts.","为受支持的 Steam 客户端添加 Zstd 解压支持。\n\n1. 暂停下载并关闭游戏。\n2. 点击“启用补丁”，允许 Windows 管理员权限请求。\n3. 补丁报告成功后，继续下载。\n\nSteam 未运行时会自动启动；完全退出或重启后需再次启用。","為受支援的 Steam 用戶端加入 Zstd 解壓支援。\n\n1. 暫停下載並關閉遊戲。\n2. 點擊「啟用補丁」，允許 Windows 管理員權限請求。\n3. 補丁回報成功後，繼續下載。\n\nSteam 未執行時會自動啟動；完全退出或重新啟動後須再次啟用。")},0,0);Button ok,cancel;l.Controls.Add(UiDialogs.Buttons(T("Cancel","取消","取消"),T("Enable patch","启用补丁","啟用補丁"),out ok,out cancel),0,1);d.Controls.Add(l);d.AcceptButton=ok;d.CancelButton=cancel;if(d.ShowDialog(this)!=DialogResult.OK)return;}Run(()=>ZstdSupport.Enable(steam,Log),()=>status.Text=T("Zstd helper reported success. Reapply after Steam restarts.","Zstd 补丁报告启用成功；Steam 重启后需再次启用。","Zstd 補丁回報啟用成功；Steam 重新啟動後需再次啟用。"));}
 void Run(Action action,Action success){if(busy)return;busy=true;UpdateState();status.Text=T("Working…","正在处理…","正在處理…");var worker=new BackgroundWorker();worker.DoWork+=(s,e)=>action();worker.RunWorkerCompleted+=(s,e)=>{busy=false;UpdateState();if(e.Error!=null){Log("ERROR: "+e.Error.Message);RefreshList(null);status.Text=T("Operation did not complete; see Diagnostics / logs.","操作未完成，可在“诊断 / 日志”中查看详情。","操作未完成，可在「診斷 / 日誌」中查看詳情。");UiDialogs.Error(this,e.Error.Message,Text,T("Close","关闭","關閉"));}else if(success!=null)success();worker.Dispose();};worker.RunWorkerAsync();}
 void Log(string text){if(InvokeRequired){Invoke((MethodInvoker)(()=>Log(text)));return;}log.AppendText(DateTime.Now.ToString("HH:mm:ss")+" "+text+Environment.NewLine);}
 string Details(){var b=new StringBuilder();b.AppendLine(Text);b.AppendLine("OS: "+Environment.OSVersion+"; x64: "+Environment.Is64BitOperatingSystem);b.AppendLine("Steam: "+steam);foreach(var g in games){b.AppendLine(g.Name+" | "+g.AppId+" | "+g.Root+" | "+RowStatus(g));var p=Profile(g);if(p!=null)b.AppendLine("Launch mode: "+p.Mode+"; EXE: "+p.Exe);RepairContext ctx;if(contexts.TryGetValue(g.Root,out ctx)){b.AppendLine(Analyzer.Render(ctx.Report));if(ctx.Plan!=null)b.AppendLine(AutoBridge.Describe(ctx.Plan));b.AppendLine(ctx.Error);}}b.AppendLine("Zstd helper target client SHA256: "+ZstdSupport.SupportedClientHash);b.AppendLine(log.Text);return b.ToString();}
 void Export(){using(var d=new SaveFileDialog{Filter="Text (*.txt)|*.txt",FileName="LegacySteamFixer-Diagnostics.txt"})if(d.ShowDialog(this)==DialogResult.OK)File.WriteAllText(d.FileName,Details(),Encoding.UTF8);}
 void Manage(){using(var d=new ThemedForm{Text=T("Diagnostics / logs","诊断 / 日志","診斷 / 日誌"),Size=new Size(850,590),StartPosition=FormStartPosition.CenterParent,Font=Font,BackColor=UiTheme.Background,ForeColor=UiTheme.Text}){var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=54,Padding=new Padding(12,8,12,4),WrapContents=false};var detail=new TextBox{Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Text=Details()};d.Controls.Add(detail);d.Controls.Add(bar);Action<string,Action> add=(name,action)=>{var b=new StyledButton{Text=name,Width=180,Height=36,Margin=new Padding(0,0,8,0)};b.Click+=(s,e)=>action();bar.Controls.Add(b);};
 add(T("Steam folder","设置 Steam 目录","設定 Steam 目錄"),()=>{using(var f=new FolderBrowserDialog())if(f.ShowDialog(d)==DialogResult.OK){steam=f.SelectedPath;steamPath.Text=steam;d.Close();Scan();}});add(T("Export diagnostics","导出诊断","匯出診斷"),()=>Export());add(T("Open injection logs","打开注入日志目录","開啟注入日誌目錄"),()=>{var p=Profile(Selected());if(p!=null&&p.Mode=="inject"){string dir=Path.GetDirectoryName(LaunchProfiles.ConfigPath(p));if(Directory.Exists(dir))System.Diagnostics.Process.Start(dir);}});d.ShowDialog(this);}}
}
static class Program {[STAThread]static void Main(){try{Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new MainForm());}catch(Exception e){MessageBox.Show(e.ToString(),"LegacySteamFixer startup error");}}}
