using System;using System.IO;using System.Runtime.InteropServices;
class SteamProbe {
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr LoadLibraryEx(string path,IntPtr file,uint flags);
 [DllImport("kernel32.dll",CharSet=CharSet.Ansi,ExactSpelling=true)]static extern IntPtr GetProcAddress(IntPtr lib,string name);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode)]static extern bool SetDllDirectory(string path);
 [UnmanagedFunctionPointer(CallingConvention.Cdecl)]delegate IntPtr Factory([MarshalAs(UnmanagedType.LPStr)]string version,IntPtr result);
 [UnmanagedFunctionPointer(CallingConvention.ThisCall)]delegate int CreatePipe(IntPtr self);
 [UnmanagedFunctionPointer(CallingConvention.ThisCall)]delegate int Connect(IntPtr self,int pipe);
 [UnmanagedFunctionPointer(CallingConvention.ThisCall)]delegate IntPtr Getter(IntPtr self,int user,int pipe,[MarshalAs(UnmanagedType.LPStr)]string version);
 [UnmanagedFunctionPointer(CallingConvention.ThisCall)]delegate IntPtr UtilsGetter(IntPtr self,int pipe,[MarshalAs(UnmanagedType.LPStr)]string version);
 [UnmanagedFunctionPointer(CallingConvention.ThisCall)]delegate void ReleaseUser(IntPtr self,int pipe,int user);
 [UnmanagedFunctionPointer(CallingConvention.ThisCall)]delegate byte ReleasePipe(IntPtr self,int pipe);
 static Delegate Slot(IntPtr obj,int n,Type t){return Marshal.GetDelegateForFunctionPointer(Marshal.ReadIntPtr(Marshal.ReadIntPtr(obj),n*IntPtr.Size),t);}
 static void Main(string[] args){if(args.Length!=2){Console.Error.WriteLine("Expected Steam directory and query file");Environment.ExitCode=1;return;}IntPtr client=IntPtr.Zero;int pipe=0,user=0;try{string root=Path.GetFullPath(args[0]);string dll=Path.Combine(root,IntPtr.Size==8?"steamclient64.dll":"steamclient.dll");Console.WriteLine("NOTE\tClient DLL: "+dll+"; version="+System.Diagnostics.FileVersionInfo.GetVersionInfo(dll).FileVersion+"; AppID="+Environment.GetEnvironmentVariable("SteamAppId"));SetDllDirectory(root);IntPtr lib=LoadLibraryEx(dll,IntPtr.Zero,8);if(lib==IntPtr.Zero)throw new Exception("LoadLibrary error="+Marshal.GetLastWin32Error());IntPtr factoryPtr=GetProcAddress(lib,"CreateInterface");if(factoryPtr==IntPtr.Zero)throw new Exception("CreateInterface export missing");var factory=(Factory)Marshal.GetDelegateForFunctionPointer(factoryPtr,typeof(Factory));bool known=IntPtr.Size==8&&Marshal.ReadByte(factoryPtr,0)==0x4c&&Marshal.ReadByte(factoryPtr,1)==0x8b&&Marshal.ReadByte(factoryPtr,2)==0x0d&&Marshal.ReadByte(factoryPtr,7)==0x4c&&Marshal.ReadByte(factoryPtr,8)==0x8b&&Marshal.ReadByte(factoryPtr,9)==0xd2&&Marshal.ReadByte(factoryPtr,10)==0x4c&&Marshal.ReadByte(factoryPtr,11)==0x8b&&Marshal.ReadByte(factoryPtr,12)==0xd9;Console.WriteLine("RESULT\tLegacySteamBridgeABI\t"+(known?"PRESENT":"UNKNOWN: factory ABI outside verified pattern"));string[] queries=File.ReadAllLines(args[1]);foreach(string v in queries)if(v.StartsWith("SteamClient",StringComparison.Ordinal))Console.WriteLine("RESULT\t"+v+"\t"+(factory(v,IntPtr.Zero)!=IntPtr.Zero?"PRESENT":"UNAVAILABLE: factory returned null"));
 // Use only the established SteamClient017 ABI, never infer vtable layout from an unknown version.
 client=factory("SteamClient017",IntPtr.Zero);if(client==IntPtr.Zero)throw new Exception("SteamClient017 unavailable; IPC probe not attempted");pipe=((CreatePipe)Slot(client,0,typeof(CreatePipe)))(client);if(pipe==0)throw new Exception("CreateSteamPipe failed; keep Steam running");user=((Connect)Slot(client,2,typeof(Connect)))(client,pipe);if(user==0)throw new Exception("ConnectToGlobalUser failed; keep Steam logged in at same privilege level");
 Console.WriteLine("NOTE\tValid Steam IPC context created; pointer availability only, game ownership/startup not tested");foreach(string v in queries){if(v.StartsWith("SteamClient",StringComparison.Ordinal))continue;if(v.StartsWith("SteamGameServer",StringComparison.Ordinal)){Console.WriteLine("RESULT\t"+v+"\tUNKNOWN: game-server context not probed");continue;}try{int slot=12;if(v.StartsWith("SteamUserStats",StringComparison.Ordinal)||v.StartsWith("STEAMUSERSTATS",StringComparison.Ordinal))slot=13;else if(v.StartsWith("SteamUser",StringComparison.Ordinal))slot=5;else if(v.StartsWith("SteamFriends",StringComparison.Ordinal))slot=8;else if(v.StartsWith("SteamUtils",StringComparison.Ordinal))slot=9;else if(v.StartsWith("SteamMatchMakingServers",StringComparison.Ordinal))slot=11;else if(v.StartsWith("SteamMatchMaking",StringComparison.Ordinal))slot=10;else if(v.StartsWith("SteamApps",StringComparison.Ordinal)||v.StartsWith("STEAMAPPS",StringComparison.Ordinal))slot=15;else if(v.StartsWith("SteamNetworking",StringComparison.Ordinal)&&v.Length==18)slot=16;else if(v.StartsWith("STEAMREMOTESTORAGE",StringComparison.Ordinal))slot=17;else if(v.StartsWith("STEAMSCREENSHOTS",StringComparison.Ordinal))slot=18;IntPtr result=slot==9?((UtilsGetter)Slot(client,slot,typeof(UtilsGetter)))(client,pipe,v):((Getter)Slot(client,slot,typeof(Getter)))(client,user,pipe,v);Console.WriteLine("RESULT\t"+v+"\t"+(result!=IntPtr.Zero?"PRESENT":"UNAVAILABLE: interface getter returned null"));}catch(Exception e){Console.WriteLine("RESULT\t"+v+"\tUNKNOWN: "+e.Message);}}}catch(Exception e){Console.Error.WriteLine(e.Message);Environment.ExitCode=1;}finally{if(client!=IntPtr.Zero&&pipe!=0){if(user!=0)((ReleaseUser)Slot(client,4,typeof(ReleaseUser)))(client,pipe,user);((ReleasePipe)Slot(client,1,typeof(ReleasePipe)))(client,pipe);}}}
}
