using System;using System.IO;using System.Text;using System.Collections.Generic;using System.Globalization;
public class SteamLaunchMode {public string Id,Name,Executable,Arguments,WorkingDirectory;public override string ToString(){return Name;}}
public static class SteamLaunchModes {
 static string CString(BinaryReader r,long end){var b=new List<byte>();while(r.BaseStream.Position<end){byte c=r.ReadByte();if(c==0)return Encoding.UTF8.GetString(b.ToArray());if(b.Count>=65536)throw new InvalidDataException("Steam string is too long");b.Add(c);}throw new InvalidDataException("Truncated Steam string");}
 static void Need(BinaryReader r,long end,int n){if(r.BaseStream.Position>end-n)throw new InvalidDataException("Truncated Steam launch cache");}
 static Dictionary<string,object> Dict(BinaryReader r,long end,string[] keys,int depth){if(depth>64)throw new InvalidDataException("Steam cache nesting limit exceeded");var d=new Dictionary<string,object>(StringComparer.OrdinalIgnoreCase);while(true){Need(r,end,1);byte type=r.ReadByte();if(type==8||type==11)return d;string key;if(keys==null)key=CString(r,end);else{Need(r,end,4);uint i=r.ReadUInt32();if(i>=keys.Length)throw new InvalidDataException("Steam key index is invalid");key=keys[i];}object v;switch(type){case 0:v=Dict(r,end,keys,depth+1);break;case 1:v=CString(r,end);break;case 2:case 4:case 6:Need(r,end,4);v=r.ReadInt32();break;case 3:Need(r,end,4);v=r.ReadSingle();break;case 7:Need(r,end,8);v=r.ReadUInt64();break;case 10:Need(r,end,8);v=r.ReadInt64();break;default:throw new InvalidDataException("Unsupported Steam value type: "+type);}if(d.ContainsKey(key))throw new InvalidDataException("Duplicate Steam cache key");d.Add(key,v);}}
 static Dictionary<string,object> Child(Dictionary<string,object> d,string key){object x;return d!=null&&d.TryGetValue(key,out x)?x as Dictionary<string,object>:null;}
 static string S(Dictionary<string,object> d,string key){object x;return d!=null&&d.TryGetValue(key,out x)&&x!=null?Convert.ToString(x,CultureInfo.InvariantCulture):"";}
 public static Dictionary<string,object> Read(Stream stream,uint appid){using(var r=new BinaryReader(stream,Encoding.UTF8)){Need(r,stream.Length,8);uint magic=r.ReadUInt32();r.ReadUInt32();if(magic!=0x07564427&&magic!=0x07564428&&magic!=0x07564429)throw new InvalidDataException("Unsupported Steam appinfo cache version");string[] keys=null;long dataEnd=stream.Length;if(magic==0x07564429){Need(r,stream.Length,8);long offset=r.ReadInt64();if(offset<16||offset>stream.Length-4)throw new InvalidDataException("Invalid Steam string table offset");long start=stream.Position;stream.Position=offset;uint count=r.ReadUInt32();if(count>1000000)throw new InvalidDataException("Steam key table is too large");keys=new string[count];for(int i=0;i<count;i++)keys[i]=CString(r,stream.Length);stream.Position=start;dataEnd=offset;}while(true){Need(r,dataEnd,4);uint id=r.ReadUInt32();if(id==0)break;Need(r,dataEnd,4);uint size=r.ReadUInt32();long end=stream.Position+size;int fixedSize=magic==0x07564427?40:60;if(size<fixedSize||end>dataEnd)throw new InvalidDataException("Invalid Steam app entry size");if(id==appid){stream.Position+=fixedSize;var d=Dict(r,end,keys,0);return Child(d,"appinfo")??d;}stream.Position=end;}throw new InvalidDataException("Game launch modes are not cached by Steam; open the game page in Steam and retry");}}
 public static List<SteamLaunchMode> ReadModes(string steam,string root,uint appid){string path=Core.Inside(steam,"appcache/appinfo.vdf");using(var f=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))return Extract(Read(f,appid),root);}
 public static string DirectoryPath(string root,string relative){string fullRoot=Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar);string full=Path.GetFullPath(Path.Combine(root,relative));if(full.Equals(fullRoot,StringComparison.OrdinalIgnoreCase)){if((File.GetAttributes(fullRoot)&FileAttributes.ReparsePoint)!=0)throw new InvalidDataException("Reparse game root rejected");return fullRoot;}return Core.Inside(root,relative);}
 public static List<SteamLaunchMode> Extract(Dictionary<string,object> app,string root){var launch=Child(Child(app,"config"),"launch");if(launch==null)throw new InvalidDataException("Steam cache has no launch modes for this game");var result=new List<SteamLaunchMode>();foreach(var p in launch){var d=p.Value as Dictionary<string,object>;if(d==null)continue;var config=Child(d,"config");string os=S(config,"oslist");bool windows=os=="";foreach(string item in os.Split(','))if(item.Trim().Equals("windows",StringComparison.OrdinalIgnoreCase))windows=true;if(!windows)continue;string type=S(d,"type");if(type!=""&&type!="default"&&type!="none")continue;if(S(config,"betakey")!=""||S(config,"ownsdlc")!="")continue;string exe=S(d,"executable");if(exe==""||!exe.EndsWith(".exe",StringComparison.OrdinalIgnoreCase))continue;exe=exe.Replace('/',Path.DirectorySeparatorChar).Replace('\\',Path.DirectorySeparatorChar);string full=Core.Inside(root,exe);if(!File.Exists(full))continue;string wd=S(d,"workingdir");if(wd=="")wd=".";wd=wd.Replace('/',Path.DirectorySeparatorChar).Replace('\\',Path.DirectorySeparatorChar);string working=DirectoryPath(root,wd);if(!Directory.Exists(working))continue;string name=S(d,"description");var localized=Child(d,"description_loc");string culture=CultureInfo.CurrentUICulture.Name.ToLowerInvariant();string translated=S(localized,culture.StartsWith("zh")?(culture.Contains("tw")||culture.Contains("hk")||culture.Contains("hant")?"tchinese":"schinese"):"english");if(translated!="")name=translated;if(name=="")name=exe;result.Add(new SteamLaunchMode{Id=p.Key,Name=name,Executable=exe,Arguments=S(d,"arguments"),WorkingDirectory=working});}result.Sort((a,b)=>{int x,y;return int.TryParse(a.Id,out x)&&int.TryParse(b.Id,out y)?x.CompareTo(y):StringComparer.Ordinal.Compare(a.Id,b.Id);});if(result.Count==0)throw new InvalidDataException("No applicable Windows launch mode is available");return result;}
}
