using System;using System.Drawing;using System.Windows.Forms;using System.Runtime.InteropServices;
class ThemedForm:Form {
 Panel body,chrome;Label caption;Button min,max,close;bool ready,loaded;FormBorderStyle requested=FormBorderStyle.Sizable;
 [DllImport("user32.dll")]static extern bool ReleaseCapture();[DllImport("user32.dll")]static extern IntPtr SendMessage(IntPtr h,int m,IntPtr w,IntPtr l);
 public new FormBorderStyle FormBorderStyle{get{return requested;}set{requested=value;base.FormBorderStyle=FormBorderStyle.None;}}
 public ThemedForm(){base.FormBorderStyle=FormBorderStyle.None;BackColor=UiTheme.Background;Padding=new Padding(1);StartPosition=FormStartPosition.CenterScreen;SetStyle(ControlStyles.OptimizedDoubleBuffer|ControlStyles.AllPaintingInWmPaint,true);
 body=new Panel{Dock=DockStyle.Fill,BackColor=UiTheme.Background,Margin=new Padding(0)};chrome=new Panel{Dock=DockStyle.Top,Height=38,BackColor=Color.FromArgb(232,238,247),Margin=new Padding(0)};caption=new Label{Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,Padding=new Padding(15,0,0,0),ForeColor=UiTheme.Text,AutoEllipsis=true};min=CaptionButton("—",()=>WindowState=FormWindowState.Minimized);max=CaptionButton("□",()=>ToggleMax());close=CaptionButton("×",()=>Close());chrome.Controls.Add(caption);chrome.Controls.Add(min);chrome.Controls.Add(max);chrome.Controls.Add(close);Controls.Add(body);Controls.Add(chrome);chrome.MouseDown+=Drag;caption.MouseDown+=Drag;chrome.DoubleClick+=(s,e)=>ToggleMax();caption.DoubleClick+=(s,e)=>ToggleMax();ready=true;TextChanged+=(s,e)=>caption.Text=Text;Paint+=(s,e)=>{using(var p=new Pen(UiTheme.Line))e.Graphics.DrawRectangle(p,0,0,Width-1,Height-1);};}
 Button CaptionButton(string text,Action click){var b=new StyledButton{Text=text,Dock=DockStyle.Right,Width=44,Margin=new Padding(0),Font=new Font("Segoe UI",12)};b.Click+=(s,e)=>click();return b;}
 void ToggleMax(){if(MaximizeBox&&requested==FormBorderStyle.Sizable)WindowState=WindowState==FormWindowState.Maximized?FormWindowState.Normal:FormWindowState.Maximized;}
 void Drag(object sender,MouseEventArgs e){if(e.Button!=MouseButtons.Left)return;ReleaseCapture();SendMessage(Handle,0xA1,new IntPtr(2),IntPtr.Zero);}
 protected override void OnControlAdded(ControlEventArgs e){base.OnControlAdded(e);if(ready&&e.Control!=body&&e.Control!=chrome){Controls.Remove(e.Control);body.Controls.Add(e.Control);}}
 protected override void OnLoad(EventArgs e){base.FormBorderStyle=FormBorderStyle.None;caption.Text=Text;caption.Font=Font;min.Visible=MinimizeBox;max.Visible=MaximizeBox;max.Enabled=requested==FormBorderStyle.Sizable;MaximizedBounds=Screen.FromControl(this).WorkingArea;if(!loaded){loaded=true;ClientSize=new Size(ClientSize.Width,ClientSize.Height+chrome.Height);}base.OnLoad(e);}
 protected override void WndProc(ref Message m){if(m.Msg==0x84&&WindowState==FormWindowState.Normal&&requested==FormBorderStyle.Sizable){long v=m.LParam.ToInt64();Point p=PointToClient(new Point((short)(v&0xffff),(short)((v>>16)&0xffff)));int edge=Math.Max(5,Font.Height/2);bool l=p.X<edge,r=p.X>=ClientSize.Width-edge,t=p.Y<edge,b=p.Y>=ClientSize.Height-edge;int hit=t?(l?13:r?14:12):b?(l?16:r?17:15):l?10:r?11:0;if(hit!=0){m.Result=new IntPtr(hit);return;}}base.WndProc(ref m);}
}
