using System;using System.Drawing;using System.Drawing.Drawing2D;using System.Windows.Forms;
static class UiTheme {
 public static readonly Color Background=Color.FromArgb(245,247,250),Text=Color.FromArgb(30,43,61),Muted=Color.FromArgb(94,109,129),Line=Color.FromArgb(225,231,239),Blue=Color.FromArgb(34,100,180);
 public static void StyleList(ListView list){list.OwnerDraw=true;list.BorderStyle=BorderStyle.None;list.BackColor=Color.White;list.ForeColor=Text;list.GridLines=false;list.HeaderStyle=ColumnHeaderStyle.Nonclickable;
 list.DrawColumnHeader+=(s,e)=>{using(var b=new SolidBrush(Color.FromArgb(239,243,249)))e.Graphics.FillRectangle(b,e.Bounds);TextRenderer.DrawText(e.Graphics,e.Header.Text,list.Font,new Rectangle(e.Bounds.X+12,e.Bounds.Y,e.Bounds.Width-16,e.Bounds.Height),Muted,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.SingleLine);using(var p=new Pen(Line))e.Graphics.DrawLine(p,e.Bounds.Left,e.Bounds.Bottom-1,e.Bounds.Right,e.Bounds.Bottom-1);};
 list.DrawItem+=(s,e)=>{if(list.View!=View.Details)e.DrawDefault=true;};list.DrawSubItem+=(s,e)=>{bool selected=e.Item.Selected;Color bg=selected?Color.FromArgb(228,239,253):(e.ItemIndex%2==0?Color.White:Color.FromArgb(250,251,253));using(var b=new SolidBrush(bg))e.Graphics.FillRectangle(b,e.Bounds);if(e.ColumnIndex==0&&selected)using(var b=new SolidBrush(Blue))e.Graphics.FillRectangle(b,e.Bounds.X,e.Bounds.Y,3,e.Bounds.Height);Color fg=e.ColumnIndex==0?Text:Muted;if(e.ColumnIndex==1&&(e.SubItem.Text.Contains("配置")||e.SubItem.Text.Contains("設定")||e.SubItem.Text.Contains("configured")||e.SubItem.Text.Contains("installed")))fg=Color.FromArgb(31,123,86);TextRenderer.DrawText(e.Graphics,e.SubItem.Text,list.Font,new Rectangle(e.Bounds.X+12,e.Bounds.Y,e.Bounds.Width-16,e.Bounds.Height),fg,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.SingleLine);};
 }
 public static Panel Input(TextBox text){text.BorderStyle=BorderStyle.None;text.Dock=DockStyle.Fill;text.BackColor=Color.White;var panel=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(9,2,9,1),Margin=new Padding(3,4,6,4)};panel.Controls.Add(text);panel.Paint+=(s,e)=>{using(var p=new Pen(text.Focused?Blue:Line))e.Graphics.DrawRectangle(p,0,0,panel.Width-1,panel.Height-1);};text.GotFocus+=(s,e)=>panel.Invalidate();text.LostFocus+=(s,e)=>panel.Invalidate();return panel;}
 public static Panel Card(Control content){var card=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(1),Margin=new Padding(3,8,3,8)};card.Controls.Add(content);card.Paint+=(s,e)=>{using(var p=new Pen(Line))e.Graphics.DrawRectangle(p,0,0,card.Width-1,card.Height-1);};return card;}
}
class StyledButton:Button {
 public bool Primary;bool hover,pressed;
 public StyledButton(){FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;UseVisualStyleBackColor=false;Cursor=Cursors.Hand;SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}
 protected override void OnMouseEnter(EventArgs e){hover=true;Invalidate();base.OnMouseEnter(e);}protected override void OnMouseLeave(EventArgs e){hover=pressed=false;Invalidate();base.OnMouseLeave(e);}protected override void OnMouseDown(MouseEventArgs e){pressed=true;Invalidate();base.OnMouseDown(e);}protected override void OnMouseUp(MouseEventArgs e){pressed=false;Invalidate();base.OnMouseUp(e);}protected override void OnEnabledChanged(EventArgs e){Invalidate();base.OnEnabledChanged(e);}
 protected override void OnPaintBackground(PaintEventArgs e){using(var background=new SolidBrush(Parent==null?UiTheme.Background:Parent.BackColor))e.Graphics.FillRectangle(background,ClientRectangle);}
 protected override void OnPaint(PaintEventArgs e){using(var background=new SolidBrush(Parent==null?UiTheme.Background:Parent.BackColor))e.Graphics.FillRectangle(background,ClientRectangle);e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;Color bg=!Enabled?Color.FromArgb(235,239,244):Primary?(pressed?Color.FromArgb(23,73,135):hover?Color.FromArgb(43,114,197):UiTheme.Blue):(pressed?Color.FromArgb(222,232,245):hover?Color.FromArgb(237,243,251):Color.White);Color fg=!Enabled?Color.FromArgb(112,125,144):Primary?Color.White:UiTheme.Text;var r=new RectangleF(1,1,Math.Max(1,Width-3),Math.Max(1,Height-3));float radius=Math.Min(5,Height/4f);using(var path=new GraphicsPath()){float d=radius*2;path.AddArc(r.X,r.Y,d,d,180,90);path.AddArc(r.Right-d,r.Y,d,d,270,90);path.AddArc(r.Right-d,r.Bottom-d,d,d,0,90);path.AddArc(r.X,r.Bottom-d,d,d,90,90);path.CloseFigure();using(var b=new SolidBrush(bg))e.Graphics.FillPath(b,path);using(var p=new Pen(Primary&&Enabled?bg:UiTheme.Line))e.Graphics.DrawPath(p,path);}using(var ink=new SolidBrush(fg))using(var format=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center,Trimming=StringTrimming.EllipsisCharacter,FormatFlags=StringFormatFlags.NoWrap})e.Graphics.DrawString(Text,Font,ink,new RectangleF(5,2,Math.Max(1,Width-10),Math.Max(1,Height-4)),format);if(Focused&&ShowFocusCues)ControlPaint.DrawFocusRectangle(e.Graphics,new Rectangle(6,6,Math.Max(1,Width-12),Math.Max(1,Height-12)),fg,bg);}
}
