using System;using System.IO;using System.Net;using System.Text;using System.Text.RegularExpressions;using System.Collections.Generic;using System.Web.Script.Serialization;
public class UpdateAsset {public string name,browser_download_url,digest;public long size;}
public class UpdateRelease {public string tag_name,html_url,body;public bool draft,prerelease;public UpdateAsset[] assets;}
public static class UpdateService {
 public const string Repository="https://github.com/yuyu107/LegacySteamFixer";
 public static int Compare(string a,string b){var pattern=@"^v?(\d+)\.(\d+)\.(\d+)(?:-test(\d+))?$";var x=Regex.Match(a??"",pattern);var y=Regex.Match(b??"",pattern);if(!x.Success||!y.Success)throw new FormatException("Unsupported release version");for(int i=1;i<=3;i++){int c=int.Parse(x.Groups[i].Value).CompareTo(int.Parse(y.Groups[i].Value));if(c!=0)return c;}if(x.Groups[4].Success!=y.Groups[4].Success)return x.Groups[4].Success?-1:1;return x.Groups[4].Success?int.Parse(x.Groups[4].Value).CompareTo(int.Parse(y.Groups[4].Value)):0;}
 public static UpdateRelease Select(string json,bool preview,string current){var entries=new JavaScriptSerializer{MaxJsonLength=4000000}.Deserialize<UpdateRelease[]>(json);UpdateRelease best=null;foreach(var r in entries){if(r.draft||(!preview&&(r.prerelease||(r.tag_name??"").Contains("-"))))continue;try{if(Compare(r.tag_name,current)<=0)continue;if(best==null||Compare(r.tag_name,best.tag_name)>0)best=r;}catch(FormatException){} }return best;}
 static HttpWebRequest Request(string url){var req=(HttpWebRequest)WebRequest.Create(url);req.UserAgent="LegacySteamFixer/"+AppInfo.Version;req.Accept="application/vnd.github+json";req.Timeout=30000;req.ReadWriteTimeout=30000;return req;}
 static string Get(string url){ServicePointManager.SecurityProtocol|=(SecurityProtocolType)3072;using(var response=Request(url).GetResponse())using(var stream=response.GetResponseStream())using(var reader=new StreamReader(stream))return reader.ReadToEnd();}
 public static UpdateRelease Check(bool preview){string all="[";for(int page=1;page<=10;page++){string raw=Get("https://api.github.com/repos/yuyu107/LegacySteamFixer/releases?per_page=100&page="+page);var rs=new JavaScriptSerializer{MaxJsonLength=4000000}.Deserialize<UpdateRelease[]>(raw);if(rs.Length==0)break;all+=(all.Length>1?",":"")+raw.Trim().Substring(1,raw.Trim().Length-2);if(rs.Length<100)break;}return Select(all+"]",preview,AppInfo.Version);}
 public static UpdateAsset Package(UpdateRelease r){string name="LegacySteamFixer-"+r.tag_name+".zip";UpdateAsset result=null;foreach(var a in r.assets??new UpdateAsset[0])if(a.name==name){if(result!=null)throw new Exception("Duplicate update package");result=a;}if(result==null)throw new Exception("Release has no complete runtime package: "+name);ValidateUrl(result.browser_download_url);return result;}
 static void ValidateUrl(string url){Uri u;if(!Uri.TryCreate(url,UriKind.Absolute,out u)||u.Scheme!="https"||u.Host!="github.com"||!u.AbsolutePath.StartsWith("/yuyu107/LegacySteamFixer/releases/download/",StringComparison.Ordinal))throw new Exception("Unexpected update asset URL");}
 public static string HashText(string text,string filename){foreach(var line in text.Split('\n')){var m=Regex.Match(line.Trim(),@"^([a-fA-F0-9]{64})\s+\*?(.+)$");if(m.Success&&m.Groups[2].Value.Trim()==filename)return m.Groups[1].Value.ToLowerInvariant();}throw new Exception("Checksum file does not identify the selected package");}
 public static void Verify(string path,string expected){if(!Regex.IsMatch(expected??"",@"^[a-fA-F0-9]{64}$")||Core.Hash(path)!=expected.ToLowerInvariant())throw new Exception("Update SHA256 verification failed");}
 public static void Download(UpdateRelease release,string destination,Action<long,long> progress){var asset=Package(release);string expected=null;if(Regex.IsMatch(asset.digest??"",@"^sha256:[a-fA-F0-9]{64}$"))expected=asset.digest.Substring(7);else{string checksum="LegacySteamFixer-"+release.tag_name+".sha256.txt";foreach(var a in release.assets??new UpdateAsset[0])if(a.name==checksum){ValidateUrl(a.browser_download_url);expected=HashText(Get(a.browser_download_url),asset.name);break;}if(expected==null)throw new Exception("Release has no SHA256 information; download was not started");}
 string temp=destination+".partial-"+Guid.NewGuid().ToString("N");try{ServicePointManager.SecurityProtocol|=(SecurityProtocolType)3072;using(var response=Request(asset.browser_download_url).GetResponse())using(var input=response.GetResponseStream())using(var output=new FileStream(temp,FileMode.CreateNew)){byte[] buffer=new byte[65536];long received=0;int n;while((n=input.Read(buffer,0,buffer.Length))>0){output.Write(buffer,0,n);received+=n;if(progress!=null)progress(received,asset.size);}if(asset.size>0&&received!=asset.size)throw new Exception("Update download is incomplete");}Verify(temp,expected);if(File.Exists(destination))File.Replace(temp,destination,null);else File.Move(temp,destination);}finally{if(File.Exists(temp))File.Delete(temp);}}
}
