using System;using System.IO;using System.Diagnostics;using System.Collections.Generic;
public static class ZstdSupport {
 public const string SupportedClientHash="d0e83c515f17ca57090c8c73664e5d61e37eae718dfa3a5cbb1e4b909548fc34";
 public static readonly Dictionary<string,string> Components=new Dictionary<string,string>{{"OldSteam_VSZa_Launcher.exe","00379bbec671d71cef53bb5375c2db17601ca1fd331b74c5975821fa92b86389"},{"steam_zstd.dll","6dea9ef6f0fd1a956dc81f63551fb27ff280082b87de4790271e5f6f3247e5bb"},{"vsza_hook.bin","fcbadbf70e968b380c564258401c02d28d0b0d676d5b0b43ecd67d54880db055"}};
 public static void VerifyComponents(){foreach(var item in Components){string path=Core.Inside(Core.Base,"zstd/"+item.Key);if(!File.Exists(path)||Core.Hash(path)!=item.Value)throw new Exception("Zstd component missing or changed: "+item.Key);}}
 public static void VerifyClient(string steam){string path=Core.Inside(steam,"steamclient.dll");if(!File.Exists(path)||Core.Hash(path)!=SupportedClientHash)throw new Exception("Zstd download support requires the supported November 2024 32-bit steamclient.dll. Current file does not match; no patch was applied.");}
 public static void Enable(string steam,Action<string> log){VerifyComponents();VerifyClient(steam);string registered=Core.SteamRoot();if(string.IsNullOrEmpty(registered)||!Path.GetFullPath(registered).TrimEnd('\\','/').Equals(Path.GetFullPath(steam).TrimEnd('\\','/'),StringComparison.OrdinalIgnoreCase))throw new Exception("Selected Steam folder differs from the registered Steam installation. Set the correct Steam folder before enabling Zstd.");
 foreach(var proc in Process.GetProcessesByName("steam"))using(proc){try{string path=proc.MainModule.FileName;if(!Path.GetDirectoryName(path).TrimEnd('\\','/').Equals(Path.GetFullPath(steam).TrimEnd('\\','/'),StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("A Steam process is running from another installation. Close it or select that installation first.");}catch(System.ComponentModel.Win32Exception){log("Could not inspect Steam path without elevation; the Zstd helper will validate its actual target.");}catch(NotSupportedException){log("Steam process inspection unavailable; the helper validates its actual target.");}}
 string helper=Core.Inside(Core.Base,"zstd/OldSteam_VSZa_Launcher.exe");log("Zstd: starting integrated helper; Steam files remain unchanged on disk.");
 using(var p=Process.Start(new ProcessStartInfo(helper){UseShellExecute=true,Verb="runas",WorkingDirectory=Path.GetDirectoryName(helper)})){if(p==null)throw new Exception("Could not start Zstd helper");while(!p.WaitForExit(1000)){}if(p.ExitCode!=0)throw new Exception("Zstd helper did not complete successfully (exit "+p.ExitCode+"). Keep the helper's full error message for diagnostics.");}
 log("Zstd helper reported success / already patched. Apply again after Steam fully exits or restarts.");
 }
}
